// P33 (05/10): the OCR languages of PDF OCR, shared by the page, its language picker and the checks of the server
// fallback (the codes: lib/ocrLanguageCodes.js; services/pdf-tools/Dockerfile installs one Tesseract model per code,
// checked by scripts/p33/ocr-languages.test.mjs). Here: the native names and the search.
// Codes are Tesseract's (tessdata). Tesseract.js downloads the same codes from cdn.jsdelivr.net.
import { LANGUAGES } from '../../lib/ocrLanguageCodes';

export { LANGUAGES };

// Each language's name in the language itself (CLDR, generated once and frozen here so that
// every browser shows and searches the same names). The search matches the English
// name, the native name and the code, ignoring case and accents, anywhere in the name:
// "fran", "fr", "français" and "francais" all find French -- the way Google Translate's
// language picker searches (before 28/09 only the English name was searched: "fran" and
// "français" found nothing). 'kur' and 'tgl' had no model on the CDN Tesseract.js loads
// from (404, checked 28/09): replaced by the models that exist, 'kmr' and 'fil'.
export const NATIVE = {
  sqi: "shqip",
  amh: "አማርኛ",
  ara: "العربية",
  asm: "অসমীয়া",
  aze: "azərbaycan",
  aze_cyrl: "азәрбајҹан (Кирил)",
  eus: "euskara",
  bel: "беларуская",
  ben: "বাংলা",
  bos: "bosanski",
  bul: "български",
  mya: "မြန်မာ",
  cat: "català",
  khm: "ខ្មែរ",
  chr: "ᏣᎳᎩ",
  chi_sim: "简体中文",
  chi_tra: "繁體中文",
  hrv: "hrvatski",
  ces: "čeština",
  dan: "dansk",
  nld: "Nederlands",
  dzo: "རྫོང་ཁ",
  est: "eesti",
  fin: "suomi",
  fra: "français",
  glg: "galego",
  kat: "ქართული",
  kat_old: "ქართული",
  deu: "Deutsch",
  ell: "Ελληνικά",
  guj: "ગુજરાતી",
  hat: "Kreyòl ayisyen",
  heb: "עברית",
  hin: "हिन्दी",
  hun: "magyar",
  isl: "íslenska",
  ind: "Bahasa Indonesia",
  gle: "Gaeilge",
  ita: "italiano",
  ita_old: "italiano",
  jpn: "日本語",
  jav: "Jawa",
  kan: "ಕನ್ನಡ",
  kaz: "қазақ тілі",
  kir: "кыргызча",
  kor: "한국어",
  lao: "ລາວ",
  lav: "latviešu",
  lit: "lietuvių",
  mkd: "македонски",
  msa: "Bahasa Melayu",
  mal: "മലയാളം",
  mlt: "Malti",
  mar: "मराठी",
  nep: "नेपाली",
  nor: "norsk",
  ori: "ଓଡ଼ିଆ",
  pan: "ਪੰਜਾਬੀ",
  fas: "فارسی",
  pol: "polski",
  por: "português",
  pus: "پښتو",
  ron: "română",
  rus: "русский",
  san: "संस्कृत भाषा",
  srp: "српски",
  srp_latn: "srpski (latinica)",
  sin: "සිංහල",
  slk: "slovenčina",
  slv: "slovenščina",
  spa: "español",
  spa_old: "español",
  swa: "Kiswahili",
  swe: "svenska",
  syr: "ܣܘܪܝܝܐ",
  tgk: "тоҷикӣ",
  tam: "தமிழ்",
  tel: "తెలుగు",
  tha: "ไทย",
  bod: "བོད་སྐད་",
  tir: "ትግርኛ",
  tur: "Türkçe",
  uig: "ئۇيغۇرچە",
  ukr: "українська",
  urd: "اردو",
  uzb: "o‘zbek",
  uzb_cyrl: "ўзбекча (Кирил)",
  vie: "Tiếng Việt",
  cym: "Cymraeg",
  yid: "ייִדיש",
  kmr: "kurdî (kurmancî)",
  fil: "Filipino",
};
export const fold = (s) => String(s).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();
export const optionLabel = (l) => (NATIVE[l.code] ? `${l.label} — ${NATIVE[l.code]}` : l.label);
export const SEARCH_KEYS = Object.fromEntries(LANGUAGES.map((l) => [l.code, fold(`${l.label} ${NATIVE[l.code] || ''} ${l.code}`)]));
export const matchLanguages = (q) => { const f = fold(q); return f ? LANGUAGES.filter((l) => SEARCH_KEYS[l.code].includes(f)) : LANGUAGES; };

