// P35 lot 3 S2: "related tools" links shown on every tool page.
// Hand-chosen neighbours, 4 to 6 per tool, most related first: the inverse
// conversion, the same family, or the logical next step of the workflow (which
// may sit in another category). Never padded with unrelated tools. The ten
// pages that already passed their own `related` list to SeoContent keep those
// choices at the head of their list here.
// Checked by scripts/p35/related-tools-check.mjs (every tool on disk has an
// entry, 4-6 links, no self link, no duplicate, every target exists and is
// indexable, every path has a name).

export const RELATED_TOOLS = {
  // pdf-tools
  '/tools/pdf-tools/pdf-merge': ['/tools/pdf-tools/pdf-split', '/tools/pdf-tools/pdf-compress', '/tools/pdf-tools/pdf-organize', '/tools/pdf-tools/jpg-to-pdf', '/tools/pdf-tools/pdf-number-pages', '/tools/pdf-tools/pdf-reorder-pages'],
  '/tools/pdf-tools/pdf-split': ['/tools/pdf-tools/pdf-merge', '/tools/pdf-tools/pdf-delete-pages', '/tools/pdf-tools/pdf-organize', '/tools/pdf-tools/pdf-compress', '/tools/pdf-tools/pdf-to-jpg'],
  '/tools/pdf-tools/pdf-compress': ['/tools/pdf-tools/pdf-merge', '/tools/pdf-tools/pdf-split', '/tools/image-tools/image-compressor', '/tools/pdf-tools/pdf-to-pdfa', '/tools/pdf-tools/pdf-protect'],
  '/tools/pdf-tools/pdf-to-word': ['/tools/pdf-tools/word-to-pdf', '/tools/pdf-tools/pdf-ocr', '/tools/pdf-tools/pdf-extract-text', '/tools/pdf-tools/pdf-to-excel', '/tools/pdf-tools/pdf-to-ppt', '/tools/pdf-tools/pdf-editor'],
  '/tools/pdf-tools/pdf-to-excel': ['/tools/pdf-tools/excel-to-pdf', '/tools/pdf-tools/pdf-to-word', '/tools/developer-tools/excel-to-csv', '/tools/pdf-tools/pdf-ocr', '/tools/pdf-tools/pdf-extract-text', '/tools/ai-tools/data-extractor'],
  '/tools/pdf-tools/pdf-to-jpg': ['/tools/pdf-tools/jpg-to-pdf', '/tools/pdf-tools/pdf-to-image', '/tools/image-tools/image-compressor', '/tools/pdf-tools/pdf-split', '/tools/pdf-tools/pdf-to-html'],
  '/tools/pdf-tools/pdf-to-image': ['/tools/pdf-tools/image-to-pdf', '/tools/pdf-tools/pdf-to-jpg', '/tools/image-tools/image-converter', '/tools/pdf-tools/pdf-ocr', '/tools/pdf-tools/pdf-to-html'],
  '/tools/pdf-tools/pdf-to-html': ['/tools/pdf-tools/html-to-pdf', '/tools/pdf-tools/pdf-to-word', '/tools/pdf-tools/pdf-extract-text', '/tools/pdf-tools/pdf-to-image', '/tools/developer-tools/html-formatter'],
  '/tools/pdf-tools/pdf-to-ppt': ['/tools/pdf-tools/ppt-to-pdf', '/tools/pdf-tools/pdf-to-word', '/tools/pdf-tools/pdf-to-excel', '/tools/pdf-tools/pdf-to-image', '/tools/pdf-tools/pdf-compress'],
  '/tools/pdf-tools/pdf-to-pdfa': ['/tools/pdf-tools/pdf-repair', '/tools/pdf-tools/pdf-compress', '/tools/pdf-tools/pdf-protect', '/tools/pdf-tools/pdf-sign', '/tools/pdf-tools/word-to-pdf'],
  '/tools/pdf-tools/word-to-pdf': ['/tools/pdf-tools/pdf-to-word', '/tools/pdf-tools/excel-to-pdf', '/tools/pdf-tools/ppt-to-pdf', '/tools/pdf-tools/pdf-merge', '/tools/pdf-tools/pdf-compress', '/tools/pdf-tools/pdf-protect'],
  '/tools/pdf-tools/jpg-to-pdf': ['/tools/pdf-tools/pdf-to-jpg', '/tools/pdf-tools/image-to-pdf', '/tools/pdf-tools/pdf-merge', '/tools/pdf-tools/pdf-compress', '/tools/image-tools/heic-to-jpg', '/tools/image-tools/image-compressor'],
  '/tools/pdf-tools/image-to-pdf': ['/tools/pdf-tools/pdf-to-image', '/tools/pdf-tools/jpg-to-pdf', '/tools/pdf-tools/pdf-merge', '/tools/pdf-tools/pdf-compress', '/tools/image-tools/image-converter', '/tools/image-tools/image-resizer'],
  '/tools/pdf-tools/excel-to-pdf': ['/tools/pdf-tools/pdf-to-excel', '/tools/pdf-tools/word-to-pdf', '/tools/pdf-tools/ppt-to-pdf', '/tools/developer-tools/csv-to-excel', '/tools/pdf-tools/pdf-merge'],
  '/tools/pdf-tools/ppt-to-pdf': ['/tools/pdf-tools/pdf-to-ppt', '/tools/pdf-tools/word-to-pdf', '/tools/pdf-tools/excel-to-pdf', '/tools/pdf-tools/pdf-compress', '/tools/pdf-tools/pdf-merge'],
  '/tools/pdf-tools/html-to-pdf': ['/tools/pdf-tools/pdf-to-html', '/tools/pdf-tools/markdown-to-pdf', '/tools/pdf-tools/text-to-pdf', '/tools/developer-tools/html-formatter', '/tools/pdf-tools/pdf-compress'],
  '/tools/pdf-tools/epub-to-pdf': ['/tools/pdf-tools/mobi-to-pdf', '/tools/converter-tools/mobi-to-epub', '/tools/pdf-tools/pdf-compress', '/tools/pdf-tools/text-to-pdf', '/tools/pdf-tools/html-to-pdf'],
  '/tools/pdf-tools/mobi-to-pdf': ['/tools/converter-tools/mobi-to-epub', '/tools/pdf-tools/epub-to-pdf', '/tools/pdf-tools/pdf-compress', '/tools/pdf-tools/text-to-pdf'],
  '/tools/pdf-tools/markdown-to-pdf': ['/tools/developer-tools/markdown-to-html', '/tools/pdf-tools/html-to-pdf', '/tools/pdf-tools/text-to-pdf', '/tools/developer-tools/markdown-editor', '/tools/developer-tools/markdown-previewer'],
  '/tools/pdf-tools/text-to-pdf': ['/tools/pdf-tools/markdown-to-pdf', '/tools/pdf-tools/word-to-pdf', '/tools/pdf-tools/html-to-pdf', '/tools/pdf-tools/pdf-extract-text', '/tools/pdf-tools/pdf-merge'],
  '/tools/pdf-tools/pdf-sign': ['/tools/pdf-tools/pdf-forms', '/tools/pdf-tools/pdf-protect', '/tools/pdf-tools/pdf-editor', '/tools/pdf-tools/pdf-watermark', '/tools/pdf-tools/pdf-merge'],
  '/tools/pdf-tools/pdf-editor': ['/tools/pdf-tools/pdf-sign', '/tools/pdf-tools/pdf-organize', '/tools/pdf-tools/pdf-forms', '/tools/pdf-tools/pdf-watermark', '/tools/pdf-tools/pdf-redact', '/tools/pdf-tools/pdf-to-word'],
  '/tools/pdf-tools/pdf-ocr': ['/tools/pdf-tools/pdf-extract-text', '/tools/pdf-tools/pdf-to-word', '/tools/pdf-tools/pdf-translate', '/tools/pdf-tools/pdf-ai-summary', '/tools/pdf-tools/pdf-to-excel'],
  '/tools/pdf-tools/pdf-forms': ['/tools/pdf-tools/pdf-sign', '/tools/pdf-tools/pdf-editor', '/tools/pdf-tools/pdf-protect', '/tools/pdf-tools/pdf-merge'],
  '/tools/pdf-tools/pdf-protect': ['/tools/pdf-tools/pdf-unlock', '/tools/pdf-tools/pdf-redact', '/tools/pdf-tools/pdf-watermark', '/tools/pdf-tools/pdf-sign', '/tools/file-tools/file-encryptor'],
  '/tools/pdf-tools/pdf-unlock': ['/tools/pdf-tools/pdf-protect', '/tools/pdf-tools/pdf-repair', '/tools/pdf-tools/pdf-merge', '/tools/pdf-tools/pdf-split', '/tools/pdf-tools/pdf-editor'],
  '/tools/pdf-tools/pdf-watermark': ['/tools/pdf-tools/pdf-protect', '/tools/pdf-tools/pdf-number-pages', '/tools/pdf-tools/pdf-sign', '/tools/pdf-tools/pdf-editor', '/tools/pdf-tools/pdf-redact'],
  '/tools/pdf-tools/pdf-rotate': ['/tools/pdf-tools/pdf-organize', '/tools/pdf-tools/pdf-crop', '/tools/pdf-tools/pdf-reorder-pages', '/tools/image-tools/image-rotate', '/tools/pdf-tools/pdf-delete-pages'],
  '/tools/pdf-tools/pdf-crop': ['/tools/pdf-tools/pdf-rotate', '/tools/pdf-tools/pdf-organize', '/tools/image-tools/image-cropper', '/tools/pdf-tools/pdf-compress', '/tools/pdf-tools/pdf-split'],
  '/tools/pdf-tools/pdf-repair': ['/tools/pdf-tools/pdf-unlock', '/tools/pdf-tools/pdf-to-pdfa', '/tools/pdf-tools/pdf-compress', '/tools/pdf-tools/pdf-extract-text', '/tools/pdf-tools/pdf-ocr'],
  '/tools/pdf-tools/pdf-compare': ['/tools/text-tools/text-comparator', '/tools/developer-tools/diff-viewer', '/tools/pdf-tools/pdf-extract-text', '/tools/file-tools/file-comparator', '/tools/pdf-tools/pdf-ocr'],
  '/tools/pdf-tools/pdf-redact': ['/tools/pdf-tools/pdf-protect', '/tools/pdf-tools/pdf-editor', '/tools/pdf-tools/pdf-watermark', '/tools/image-tools/image-pixelator', '/tools/pdf-tools/pdf-delete-pages'],
  '/tools/pdf-tools/pdf-translate': ['/tools/ai-tools/ai-translator', '/tools/pdf-tools/pdf-ai-summary', '/tools/pdf-tools/pdf-extract-text', '/tools/pdf-tools/pdf-ocr', '/tools/pdf-tools/pdf-to-word'],
  '/tools/pdf-tools/pdf-organize': ['/tools/pdf-tools/pdf-reorder-pages', '/tools/pdf-tools/pdf-delete-pages', '/tools/pdf-tools/pdf-rotate', '/tools/pdf-tools/pdf-merge', '/tools/pdf-tools/pdf-split', '/tools/pdf-tools/pdf-editor'],
  '/tools/pdf-tools/pdf-reorder-pages': ['/tools/pdf-tools/pdf-organize', '/tools/pdf-tools/pdf-delete-pages', '/tools/pdf-tools/pdf-rotate', '/tools/pdf-tools/pdf-merge', '/tools/pdf-tools/pdf-split'],
  '/tools/pdf-tools/pdf-delete-pages': ['/tools/pdf-tools/pdf-organize', '/tools/pdf-tools/pdf-split', '/tools/pdf-tools/pdf-reorder-pages', '/tools/pdf-tools/pdf-merge', '/tools/pdf-tools/pdf-compress'],
  '/tools/pdf-tools/pdf-number-pages': ['/tools/pdf-tools/pdf-merge', '/tools/pdf-tools/pdf-watermark', '/tools/pdf-tools/pdf-organize', '/tools/pdf-tools/pdf-reorder-pages', '/tools/pdf-tools/pdf-editor'],
  '/tools/pdf-tools/pdf-extract-text': ['/tools/pdf-tools/pdf-ocr', '/tools/pdf-tools/pdf-to-word', '/tools/pdf-tools/pdf-ai-summary', '/tools/pdf-tools/pdf-translate', '/tools/text-tools/word-counter', '/tools/pdf-tools/text-to-pdf'],
  '/tools/pdf-tools/pdf-ai-summary': ['/tools/ai-tools/text-summarizer', '/tools/pdf-tools/pdf-translate', '/tools/pdf-tools/pdf-extract-text', '/tools/pdf-tools/pdf-ocr', '/tools/ai-tools/keyword-extractor'],
  // image-tools
  '/tools/image-tools/image-compressor': ['/tools/image-tools/image-resizer', '/tools/image-tools/image-converter', '/tools/image-tools/jpg-to-webp', '/tools/pdf-tools/image-to-pdf', '/tools/gif-tools/gif-compressor', '/tools/pdf-tools/pdf-compress'],
  '/tools/image-tools/image-converter': ['/tools/image-tools/image-compressor', '/tools/image-tools/image-resizer', '/tools/image-tools/heic-to-jpg', '/tools/image-tools/png-to-jpg', '/tools/image-tools/jpg-to-png', '/tools/pdf-tools/image-to-pdf'],
  '/tools/image-tools/image-resizer': ['/tools/image-tools/image-cropper', '/tools/image-tools/image-compressor', '/tools/ai-tools/image-upscaler', '/tools/image-tools/image-converter', '/tools/image-tools/image-rotate', '/tools/developer-tools/aspect-ratio'],
  '/tools/image-tools/image-cropper': ['/tools/image-tools/image-resizer', '/tools/image-tools/image-rotate', '/tools/image-tools/round-corners', '/tools/image-tools/image-editor', '/tools/pdf-tools/pdf-crop'],
  '/tools/image-tools/image-editor': ['/tools/image-tools/image-cropper', '/tools/image-tools/brightness-contrast', '/tools/image-tools/add-text-to-image', '/tools/image-tools/image-resizer', '/tools/image-tools/image-rotate', '/tools/ai-tools/background-remover'],
  '/tools/image-tools/image-flip': ['/tools/image-tools/image-rotate', '/tools/image-tools/image-cropper', '/tools/image-tools/image-editor', '/tools/video-tools/video-rotator'],
  '/tools/image-tools/image-rotate': ['/tools/image-tools/image-flip', '/tools/image-tools/image-cropper', '/tools/pdf-tools/pdf-rotate', '/tools/video-tools/video-rotator', '/tools/image-tools/image-editor'],
  '/tools/image-tools/image-blur': ['/tools/image-tools/image-pixelator', '/tools/image-tools/add-vignette', '/tools/image-tools/add-noise', '/tools/image-tools/image-editor', '/tools/video-tools/video-filter'],
  '/tools/image-tools/image-inverter': ['/tools/image-tools/grayscale-converter', '/tools/image-tools/sepia-filter', '/tools/image-tools/brightness-contrast', '/tools/image-tools/image-editor', '/tools/video-tools/video-filter'],
  '/tools/image-tools/image-pixelator': ['/tools/image-tools/image-blur', '/tools/image-tools/add-noise', '/tools/image-tools/image-editor', '/tools/pdf-tools/pdf-redact'],
  '/tools/image-tools/image-comparison': ['/tools/image-tools/image-compressor', '/tools/image-tools/duplicate-image-finder', '/tools/image-tools/image-metadata', '/tools/pdf-tools/pdf-compare', '/tools/file-tools/file-comparator'],
  '/tools/image-tools/image-metadata': ['/tools/file-tools/file-metadata', '/tools/image-tools/image-compressor', '/tools/image-tools/duplicate-image-finder', '/tools/video-tools/video-metadata', '/tools/audio-tools/audio-metadata'],
  '/tools/image-tools/image-to-base64': ['/tools/file-tools/base64-encoder', '/tools/developer-tools/base64-encoder', '/tools/image-tools/image-compressor', '/tools/image-tools/image-resizer'],
  '/tools/image-tools/add-border-to-image': ['/tools/image-tools/round-corners', '/tools/image-tools/add-text-to-image', '/tools/image-tools/add-vignette', '/tools/image-tools/image-editor', '/tools/image-tools/image-resizer'],
  '/tools/image-tools/add-text-to-image': ['/tools/image-tools/image-editor', '/tools/image-tools/add-border-to-image', '/tools/pdf-tools/pdf-watermark', '/tools/video-tools/video-watermark', '/tools/image-tools/image-cropper'],
  '/tools/image-tools/add-noise': ['/tools/image-tools/add-vignette', '/tools/image-tools/image-blur', '/tools/image-tools/sepia-filter', '/tools/image-tools/image-pixelator', '/tools/image-tools/grayscale-converter'],
  '/tools/image-tools/add-vignette': ['/tools/image-tools/add-noise', '/tools/image-tools/sepia-filter', '/tools/image-tools/image-blur', '/tools/image-tools/brightness-contrast', '/tools/image-tools/add-border-to-image'],
  '/tools/image-tools/brightness-contrast': ['/tools/image-tools/image-editor', '/tools/image-tools/grayscale-converter', '/tools/image-tools/sepia-filter', '/tools/image-tools/image-inverter', '/tools/video-tools/video-filter', '/tools/image-tools/add-vignette'],
  '/tools/image-tools/grayscale-converter': ['/tools/image-tools/sepia-filter', '/tools/image-tools/image-inverter', '/tools/image-tools/brightness-contrast', '/tools/video-tools/video-filter', '/tools/image-tools/image-editor'],
  '/tools/image-tools/sepia-filter': ['/tools/image-tools/grayscale-converter', '/tools/image-tools/add-vignette', '/tools/image-tools/add-noise', '/tools/image-tools/brightness-contrast', '/tools/video-tools/video-filter'],
  '/tools/image-tools/round-corners': ['/tools/image-tools/add-border-to-image', '/tools/image-tools/image-cropper', '/tools/image-tools/image-resizer', '/tools/image-tools/png-to-ico', '/tools/image-tools/image-editor'],
  '/tools/image-tools/duplicate-image-finder': ['/tools/image-tools/image-comparison', '/tools/file-tools/file-comparator', '/tools/image-tools/image-metadata', '/tools/image-tools/image-compressor'],
  '/tools/image-tools/jpg-to-png': ['/tools/image-tools/png-to-jpg', '/tools/image-tools/jpg-to-webp', '/tools/image-tools/image-converter', '/tools/ai-tools/background-remover', '/tools/image-tools/image-compressor'],
  '/tools/image-tools/jpg-to-webp': ['/tools/image-tools/webp-to-jpg', '/tools/image-tools/png-to-webp', '/tools/image-tools/jpg-to-png', '/tools/image-tools/image-compressor', '/tools/image-tools/image-converter'],
  '/tools/image-tools/png-to-jpg': ['/tools/image-tools/jpg-to-png', '/tools/image-tools/png-to-webp', '/tools/image-tools/image-compressor', '/tools/pdf-tools/jpg-to-pdf', '/tools/image-tools/image-converter'],
  '/tools/image-tools/png-to-webp': ['/tools/image-tools/webp-to-png', '/tools/image-tools/jpg-to-webp', '/tools/image-tools/png-to-jpg', '/tools/image-tools/image-compressor', '/tools/image-tools/image-converter'],
  '/tools/image-tools/png-to-ico': ['/tools/image-tools/ico-to-png', '/tools/image-tools/svg-to-png', '/tools/image-tools/image-resizer', '/tools/image-tools/round-corners', '/tools/image-tools/image-converter'],
  '/tools/image-tools/webp-to-jpg': ['/tools/image-tools/jpg-to-webp', '/tools/image-tools/webp-to-png', '/tools/image-tools/png-to-jpg', '/tools/image-tools/image-converter', '/tools/image-tools/image-compressor'],
  '/tools/image-tools/webp-to-png': ['/tools/image-tools/png-to-webp', '/tools/image-tools/webp-to-jpg', '/tools/image-tools/jpg-to-png', '/tools/image-tools/image-converter', '/tools/image-tools/image-compressor'],
  '/tools/image-tools/bmp-to-png': ['/tools/image-tools/png-to-jpg', '/tools/image-tools/image-converter', '/tools/image-tools/tiff-to-png', '/tools/image-tools/image-compressor', '/tools/pdf-tools/image-to-pdf'],
  '/tools/image-tools/svg-to-png': ['/tools/image-tools/png-to-ico', '/tools/image-tools/image-converter', '/tools/image-tools/image-resizer', '/tools/image-tools/png-to-jpg', '/tools/image-tools/image-compressor'],
  '/tools/image-tools/heic-to-jpg': ['/tools/image-tools/heic-to-png', '/tools/image-tools/image-converter', '/tools/image-tools/image-compressor', '/tools/pdf-tools/jpg-to-pdf', '/tools/image-tools/image-metadata'],
  '/tools/image-tools/heic-to-png': ['/tools/image-tools/heic-to-jpg', '/tools/image-tools/image-converter', '/tools/image-tools/png-to-jpg', '/tools/image-tools/image-compressor', '/tools/pdf-tools/image-to-pdf'],
  '/tools/image-tools/ico-to-png': ['/tools/image-tools/png-to-ico', '/tools/image-tools/svg-to-png', '/tools/image-tools/image-converter', '/tools/image-tools/image-resizer'],
  '/tools/image-tools/tiff-to-jpg': ['/tools/image-tools/tiff-to-png', '/tools/image-tools/image-converter', '/tools/image-tools/image-compressor', '/tools/pdf-tools/image-to-pdf', '/tools/image-tools/png-to-jpg'],
  '/tools/image-tools/tiff-to-png': ['/tools/image-tools/tiff-to-jpg', '/tools/image-tools/image-converter', '/tools/image-tools/png-to-jpg', '/tools/image-tools/image-compressor', '/tools/pdf-tools/image-to-pdf'],
  '/tools/image-tools/gif-to-png': ['/tools/gif-tools/image-to-gif', '/tools/gif-tools/gif-to-apng', '/tools/image-tools/png-to-jpg', '/tools/image-tools/image-converter', '/tools/gif-tools/gif-to-mp4'],
  // gif-tools
  '/tools/gif-tools/apng-to-gif': ['/tools/gif-tools/gif-to-apng', '/tools/gif-tools/gif-compressor', '/tools/image-tools/gif-to-png', '/tools/gif-tools/gif-to-mp4', '/tools/gif-tools/gif-maker'],
  '/tools/gif-tools/avi-to-gif': ['/tools/gif-tools/video-to-gif', '/tools/gif-tools/mp4-to-gif', '/tools/gif-tools/mov-to-gif', '/tools/gif-tools/gif-compressor', '/tools/video-tools/video-converter', '/tools/video-tools/video-trimmer'],
  '/tools/gif-tools/mov-to-gif': ['/tools/gif-tools/mp4-to-gif', '/tools/gif-tools/video-to-gif', '/tools/gif-tools/avi-to-gif', '/tools/gif-tools/gif-compressor', '/tools/video-tools/video-converter', '/tools/gif-tools/gif-to-mp4'],
  '/tools/gif-tools/mp4-to-gif': ['/tools/gif-tools/gif-to-mp4', '/tools/gif-tools/video-to-gif', '/tools/gif-tools/mov-to-gif', '/tools/gif-tools/gif-compressor', '/tools/video-tools/video-trimmer', '/tools/gif-tools/webm-to-gif'],
  '/tools/gif-tools/webm-to-gif': ['/tools/gif-tools/mp4-to-gif', '/tools/gif-tools/video-to-gif', '/tools/gif-tools/gif-compressor', '/tools/gif-tools/gif-to-mp4', '/tools/video-tools/video-converter'],
  '/tools/gif-tools/video-to-gif': ['/tools/gif-tools/gif-to-mp4', '/tools/gif-tools/mp4-to-gif', '/tools/gif-tools/mov-to-gif', '/tools/gif-tools/gif-compressor', '/tools/video-tools/video-trimmer', '/tools/video-tools/video-screenshot'],
  '/tools/gif-tools/gif-to-mp4': ['/tools/gif-tools/mp4-to-gif', '/tools/gif-tools/video-to-gif', '/tools/gif-tools/gif-compressor', '/tools/video-tools/video-compressor', '/tools/video-tools/video-converter'],
  '/tools/gif-tools/gif-to-apng': ['/tools/gif-tools/apng-to-gif', '/tools/gif-tools/gif-compressor', '/tools/image-tools/gif-to-png', '/tools/gif-tools/gif-to-mp4'],
  '/tools/gif-tools/image-to-gif': ['/tools/gif-tools/gif-maker', '/tools/gif-tools/gif-compressor', '/tools/gif-tools/gif-to-mp4', '/tools/image-tools/gif-to-png', '/tools/image-tools/image-resizer'],
  '/tools/gif-tools/gif-maker': ['/tools/gif-tools/image-to-gif', '/tools/gif-tools/gif-compressor', '/tools/gif-tools/video-to-gif', '/tools/gif-tools/gif-to-mp4', '/tools/image-tools/image-resizer'],
  '/tools/gif-tools/gif-compressor': ['/tools/gif-tools/gif-to-mp4', '/tools/image-tools/image-compressor', '/tools/gif-tools/mp4-to-gif', '/tools/gif-tools/video-to-gif', '/tools/gif-tools/gif-maker', '/tools/video-tools/video-compressor'],
  // audio-tools
  '/tools/audio-tools/audio-converter': ['/tools/audio-tools/audio-compressor', '/tools/video-tools/video-to-audio', '/tools/audio-tools/audio-trimmer', '/tools/audio-tools/audio-merger', '/tools/audio-tools/audio-metadata', '/tools/video-tools/video-converter'],
  '/tools/audio-tools/audio-compressor': ['/tools/audio-tools/audio-converter', '/tools/video-tools/video-compressor', '/tools/audio-tools/audio-trimmer', '/tools/audio-tools/audio-metadata', '/tools/audio-tools/audio-booster'],
  '/tools/audio-tools/audio-trimmer': ['/tools/audio-tools/audio-splitter', '/tools/audio-tools/audio-merger', '/tools/audio-tools/audio-converter', '/tools/video-tools/video-trimmer', '/tools/audio-tools/audio-waveform'],
  '/tools/audio-tools/audio-merger': ['/tools/audio-tools/audio-splitter', '/tools/audio-tools/audio-trimmer', '/tools/video-tools/video-merger', '/tools/audio-tools/audio-converter', '/tools/audio-tools/audio-booster'],
  '/tools/audio-tools/audio-splitter': ['/tools/audio-tools/audio-merger', '/tools/audio-tools/audio-trimmer', '/tools/audio-tools/audio-waveform', '/tools/audio-tools/audio-converter', '/tools/video-tools/video-trimmer'],
  '/tools/audio-tools/audio-booster': ['/tools/audio-tools/audio-equalizer', '/tools/audio-tools/audio-compressor', '/tools/audio-tools/audio-trimmer', '/tools/audio-tools/audio-converter', '/tools/audio-tools/audio-waveform'],
  '/tools/audio-tools/audio-equalizer': ['/tools/audio-tools/audio-booster', '/tools/audio-tools/audio-waveform', '/tools/audio-tools/audio-converter', '/tools/audio-tools/audio-trimmer', '/tools/video-tools/media-player'],
  '/tools/audio-tools/audio-metadata': ['/tools/video-tools/video-metadata', '/tools/image-tools/image-metadata', '/tools/file-tools/file-metadata', '/tools/audio-tools/audio-converter', '/tools/audio-tools/audio-waveform'],
  '/tools/audio-tools/audio-waveform': ['/tools/audio-tools/audio-trimmer', '/tools/audio-tools/audio-splitter', '/tools/audio-tools/audio-equalizer', '/tools/audio-tools/audio-metadata', '/tools/video-tools/media-player'],
  '/tools/audio-tools/audio-to-text': ['/tools/ai-tools/audio-transcriber', '/tools/audio-tools/voice-recorder', '/tools/video-tools/subtitle-generator', '/tools/ai-tools/text-summarizer', '/tools/ai-tools/ai-translator'],
  '/tools/audio-tools/voice-recorder': ['/tools/audio-tools/audio-to-text', '/tools/audio-tools/audio-trimmer', '/tools/audio-tools/audio-converter', '/tools/video-tools/screen-recorder', '/tools/audio-tools/audio-booster', '/tools/ai-tools/audio-transcriber'],
  // video-tools
  '/tools/video-tools/video-converter': ['/tools/video-tools/video-compressor', '/tools/video-tools/video-to-audio', '/tools/video-tools/video-to-gif', '/tools/audio-tools/audio-converter', '/tools/video-tools/video-metadata', '/tools/video-tools/video-trimmer'],
  '/tools/video-tools/video-compressor': ['/tools/video-tools/video-converter', '/tools/video-tools/video-resizer', '/tools/video-tools/video-trimmer', '/tools/audio-tools/audio-compressor', '/tools/video-tools/video-metadata'],
  '/tools/video-tools/video-trimmer': ['/tools/video-tools/video-merger', '/tools/video-tools/video-compressor', '/tools/audio-tools/audio-trimmer', '/tools/video-tools/video-to-gif', '/tools/video-tools/video-screenshot', '/tools/video-tools/video-converter'],
  '/tools/video-tools/video-merger': ['/tools/video-tools/video-trimmer', '/tools/audio-tools/audio-merger', '/tools/video-tools/video-converter', '/tools/video-tools/video-compressor', '/tools/video-tools/video-resizer'],
  '/tools/video-tools/video-resizer': ['/tools/video-tools/video-compressor', '/tools/video-tools/video-rotator', '/tools/video-tools/video-converter', '/tools/image-tools/image-resizer', '/tools/developer-tools/aspect-ratio', '/tools/video-tools/video-trimmer'],
  '/tools/video-tools/video-rotator': ['/tools/video-tools/video-resizer', '/tools/image-tools/image-rotate', '/tools/image-tools/image-flip', '/tools/video-tools/video-converter', '/tools/video-tools/video-trimmer'],
  '/tools/video-tools/video-filter': ['/tools/image-tools/grayscale-converter', '/tools/image-tools/sepia-filter', '/tools/image-tools/brightness-contrast', '/tools/video-tools/video-watermark', '/tools/video-tools/video-converter'],
  '/tools/video-tools/video-watermark': ['/tools/video-tools/video-filter', '/tools/pdf-tools/pdf-watermark', '/tools/image-tools/add-text-to-image', '/tools/video-tools/video-trimmer', '/tools/video-tools/video-compressor'],
  '/tools/video-tools/video-metadata': ['/tools/audio-tools/audio-metadata', '/tools/image-tools/image-metadata', '/tools/file-tools/file-metadata', '/tools/video-tools/video-converter', '/tools/video-tools/media-player'],
  '/tools/video-tools/video-screenshot': ['/tools/video-tools/video-to-gif', '/tools/image-tools/image-converter', '/tools/image-tools/image-cropper', '/tools/video-tools/media-player', '/tools/video-tools/video-trimmer'],
  '/tools/video-tools/video-to-audio': ['/tools/audio-tools/audio-converter', '/tools/ai-tools/audio-transcriber', '/tools/audio-tools/audio-trimmer', '/tools/video-tools/video-converter', '/tools/audio-tools/audio-compressor'],
  '/tools/video-tools/video-to-gif': ['/tools/gif-tools/gif-to-mp4', '/tools/gif-tools/gif-compressor', '/tools/gif-tools/mp4-to-gif', '/tools/video-tools/video-screenshot', '/tools/video-tools/video-trimmer', '/tools/video-tools/video-converter'],
  '/tools/video-tools/media-player': ['/tools/video-tools/video-metadata', '/tools/audio-tools/audio-metadata', '/tools/video-tools/video-converter', '/tools/audio-tools/audio-waveform', '/tools/video-tools/video-screenshot'],
  '/tools/video-tools/screen-recorder': ['/tools/audio-tools/voice-recorder', '/tools/video-tools/video-trimmer', '/tools/video-tools/video-compressor', '/tools/video-tools/video-converter', '/tools/video-tools/video-to-gif'],
  '/tools/video-tools/subtitle-generator': ['/tools/ai-tools/audio-transcriber', '/tools/audio-tools/audio-to-text', '/tools/ai-tools/ai-translator', '/tools/video-tools/media-player', '/tools/video-tools/video-to-audio'],
  // text-tools
  '/tools/text-tools/word-counter': ['/tools/text-tools/character-counter', '/tools/text-tools/text-truncator', '/tools/ai-tools/text-summarizer', '/tools/text-tools/case-converter', '/tools/pdf-tools/pdf-extract-text'],
  '/tools/text-tools/character-counter': ['/tools/text-tools/word-counter', '/tools/text-tools/text-truncator', '/tools/text-tools/whitespace-remover', '/tools/text-tools/case-converter', '/tools/developer-tools/unicode-converter'],
  '/tools/text-tools/case-converter': ['/tools/text-tools/word-counter', '/tools/text-tools/find-replace', '/tools/text-tools/whitespace-remover', '/tools/text-tools/text-sorter', '/tools/ai-tools/grammar-fixer'],
  '/tools/text-tools/text-reverser': ['/tools/text-tools/text-sorter', '/tools/text-tools/case-converter', '/tools/text-tools/text-repeater', '/tools/text-tools/ascii-art', '/tools/text-tools/find-replace'],
  '/tools/text-tools/text-sorter': ['/tools/text-tools/duplicate-remover', '/tools/text-tools/text-to-list', '/tools/text-tools/text-reverser', '/tools/text-tools/whitespace-remover', '/tools/text-tools/find-replace'],
  '/tools/text-tools/text-comparator': ['/tools/developer-tools/diff-viewer', '/tools/pdf-tools/pdf-compare', '/tools/file-tools/file-comparator', '/tools/text-tools/whitespace-remover'],
  '/tools/text-tools/text-repeater': ['/tools/text-tools/lorem-ipsum', '/tools/text-tools/text-to-list', '/tools/text-tools/text-reverser', '/tools/text-tools/case-converter', '/tools/text-tools/character-counter'],
  '/tools/text-tools/text-truncator': ['/tools/text-tools/character-counter', '/tools/text-tools/word-counter', '/tools/ai-tools/text-summarizer', '/tools/text-tools/whitespace-remover'],
  '/tools/text-tools/text-encryptor': ['/tools/file-tools/file-encryptor', '/tools/developer-tools/hash-generator', '/tools/developer-tools/password-generator', '/tools/developer-tools/base64-encoder', '/tools/pdf-tools/pdf-protect'],
  '/tools/text-tools/text-to-list': ['/tools/text-tools/text-sorter', '/tools/text-tools/duplicate-remover', '/tools/text-tools/whitespace-remover', '/tools/text-tools/find-replace', '/tools/text-tools/case-converter'],
  '/tools/text-tools/find-replace': ['/tools/developer-tools/regex-tester', '/tools/text-tools/whitespace-remover', '/tools/text-tools/case-converter', '/tools/text-tools/duplicate-remover', '/tools/text-tools/text-sorter'],
  '/tools/text-tools/duplicate-remover': ['/tools/text-tools/text-sorter', '/tools/text-tools/whitespace-remover', '/tools/text-tools/text-to-list', '/tools/text-tools/find-replace', '/tools/text-tools/text-comparator'],
  '/tools/text-tools/whitespace-remover': ['/tools/text-tools/duplicate-remover', '/tools/text-tools/find-replace', '/tools/text-tools/text-sorter', '/tools/text-tools/character-counter', '/tools/text-tools/text-to-list'],
  '/tools/text-tools/lorem-ipsum': ['/tools/text-tools/text-repeater', '/tools/text-tools/word-counter', '/tools/ai-tools/ai-writer', '/tools/text-tools/character-counter'],
  '/tools/text-tools/ascii-art': ['/tools/text-tools/case-converter', '/tools/text-tools/text-reverser', '/tools/image-tools/add-text-to-image', '/tools/text-tools/text-repeater'],
  '/tools/text-tools/sticky-notes': ['/tools/text-tools/text-to-list', '/tools/text-tools/text-encryptor', '/tools/text-tools/word-counter', '/tools/audio-tools/voice-recorder'],
  '/tools/text-tools/url-encoder': ['/tools/developer-tools/url-parser', '/tools/developer-tools/base64-encoder', '/tools/developer-tools/html-encoder', '/tools/developer-tools/unicode-converter', '/tools/developer-tools/hex-to-text'],
  // file-tools
  '/tools/file-tools/zip-creator': ['/tools/file-tools/zip-extractor', '/tools/file-tools/file-encryptor', '/tools/file-tools/file-splitter', '/tools/file-tools/tar-extractor'],
  '/tools/file-tools/zip-extractor': ['/tools/file-tools/zip-creator', '/tools/file-tools/tar-extractor', '/tools/file-tools/file-metadata', '/tools/developer-tools/hash-generator', '/tools/file-tools/file-comparator'],
  '/tools/file-tools/tar-extractor': ['/tools/file-tools/zip-extractor', '/tools/file-tools/zip-creator', '/tools/file-tools/file-metadata', '/tools/developer-tools/hash-generator'],
  '/tools/file-tools/file-converter': ['/tools/developer-tools/csv-to-json', '/tools/developer-tools/json-to-csv', '/tools/developer-tools/json-formatter', '/tools/pdf-tools/text-to-pdf', '/tools/developer-tools/markdown-to-html'],
  '/tools/file-tools/file-comparator': ['/tools/developer-tools/hash-generator', '/tools/text-tools/text-comparator', '/tools/developer-tools/diff-viewer', '/tools/pdf-tools/pdf-compare', '/tools/image-tools/duplicate-image-finder', '/tools/file-tools/file-metadata'],
  '/tools/file-tools/file-encryptor': ['/tools/text-tools/text-encryptor', '/tools/pdf-tools/pdf-protect', '/tools/file-tools/zip-creator', '/tools/developer-tools/password-generator', '/tools/developer-tools/hash-generator'],
  '/tools/file-tools/file-metadata': ['/tools/image-tools/image-metadata', '/tools/audio-tools/audio-metadata', '/tools/video-tools/video-metadata', '/tools/file-tools/file-comparator', '/tools/developer-tools/hash-generator'],
  '/tools/file-tools/file-splitter': ['/tools/file-tools/zip-creator', '/tools/pdf-tools/pdf-split', '/tools/audio-tools/audio-splitter', '/tools/developer-tools/hash-generator', '/tools/file-tools/file-encryptor'],
  '/tools/file-tools/base64-encoder': ['/tools/image-tools/image-to-base64', '/tools/developer-tools/base64-encoder', '/tools/developer-tools/hash-generator', '/tools/file-tools/file-metadata'],
  // qr-barcodes-tools
  '/tools/qr-barcodes-tools/qr-generator': ['/tools/qr-barcodes-tools/qr-scanner', '/tools/qr-barcodes-tools/barcode-generator', '/tools/developer-tools/url-parser', '/tools/developer-tools/password-generator'],
  '/tools/qr-barcodes-tools/qr-scanner': ['/tools/qr-barcodes-tools/qr-generator', '/tools/qr-barcodes-tools/barcode-generator', '/tools/developer-tools/url-parser', '/tools/image-tools/image-cropper'],
  '/tools/qr-barcodes-tools/barcode-generator': ['/tools/qr-barcodes-tools/qr-generator', '/tools/qr-barcodes-tools/qr-scanner', '/tools/image-tools/svg-to-png', '/tools/image-tools/image-resizer'],
  // converter-tools
  '/tools/converter-tools/color-converter': ['/tools/developer-tools/color-picker', '/tools/developer-tools/css-formatter', '/tools/developer-tools/number-base-converter', '/tools/developer-tools/scss-to-css'],
  '/tools/converter-tools/currency-converter': ['/tools/converter-tools/unit-converter', '/tools/math-tools/percentage-calculator', '/tools/math-tools/scientific-calculator', '/tools/math-tools/statistics-calculator'],
  '/tools/converter-tools/unit-converter': ['/tools/converter-tools/currency-converter', '/tools/math-tools/scientific-calculator', '/tools/math-tools/percentage-calculator', '/tools/math-tools/number-base-converter', '/tools/math-tools/fraction-calculator'],
  '/tools/converter-tools/mobi-to-epub': ['/tools/pdf-tools/mobi-to-pdf', '/tools/pdf-tools/epub-to-pdf', '/tools/pdf-tools/text-to-pdf', '/tools/file-tools/file-metadata'],
  // developer-tools
  '/tools/developer-tools/json-formatter': ['/tools/developer-tools/json-minifier', '/tools/developer-tools/json-to-csv', '/tools/developer-tools/json-to-yaml', '/tools/developer-tools/json-to-typescript', '/tools/developer-tools/xml-to-json', '/tools/developer-tools/code-formatter'],
  '/tools/developer-tools/json-minifier': ['/tools/developer-tools/json-formatter', '/tools/developer-tools/js-minifier', '/tools/developer-tools/code-minifier', '/tools/developer-tools/json-to-csv'],
  '/tools/developer-tools/json-to-csv': ['/tools/developer-tools/csv-to-json', '/tools/developer-tools/csv-to-excel', '/tools/developer-tools/json-formatter', '/tools/developer-tools/excel-to-json', '/tools/developer-tools/json-to-xml'],
  '/tools/developer-tools/json-to-xml': ['/tools/developer-tools/xml-to-json', '/tools/developer-tools/xml-formatter', '/tools/developer-tools/json-formatter', '/tools/developer-tools/json-to-yaml', '/tools/developer-tools/json-to-csv'],
  '/tools/developer-tools/json-to-yaml': ['/tools/developer-tools/yaml-to-json', '/tools/developer-tools/json-to-toml', '/tools/developer-tools/json-formatter', '/tools/developer-tools/json-to-xml', '/tools/developer-tools/env-to-json'],
  '/tools/developer-tools/json-to-toml': ['/tools/developer-tools/toml-to-json', '/tools/developer-tools/json-to-yaml', '/tools/developer-tools/json-formatter', '/tools/developer-tools/yaml-to-json', '/tools/developer-tools/env-to-json'],
  '/tools/developer-tools/json-to-typescript': ['/tools/developer-tools/json-to-python', '/tools/developer-tools/json-to-go', '/tools/developer-tools/json-to-rust', '/tools/developer-tools/json-to-csharp', '/tools/developer-tools/json-formatter', '/tools/developer-tools/typescript-to-js'],
  '/tools/developer-tools/json-to-python': ['/tools/developer-tools/json-to-typescript', '/tools/developer-tools/json-to-go', '/tools/developer-tools/json-to-rust', '/tools/developer-tools/json-to-php', '/tools/developer-tools/json-to-csharp', '/tools/developer-tools/json-formatter'],
  '/tools/developer-tools/json-to-go': ['/tools/developer-tools/json-to-rust', '/tools/developer-tools/json-to-typescript', '/tools/developer-tools/json-to-python', '/tools/developer-tools/json-to-csharp', '/tools/developer-tools/json-formatter'],
  '/tools/developer-tools/json-to-php': ['/tools/developer-tools/json-to-python', '/tools/developer-tools/json-to-typescript', '/tools/developer-tools/json-to-csharp', '/tools/developer-tools/json-to-go', '/tools/developer-tools/json-formatter'],
  '/tools/developer-tools/json-to-csharp': ['/tools/developer-tools/json-to-typescript', '/tools/developer-tools/json-to-go', '/tools/developer-tools/json-to-python', '/tools/developer-tools/json-to-rust', '/tools/developer-tools/json-formatter'],
  '/tools/developer-tools/json-to-rust': ['/tools/developer-tools/json-to-go', '/tools/developer-tools/json-to-typescript', '/tools/developer-tools/json-to-csharp', '/tools/developer-tools/json-to-python', '/tools/developer-tools/json-to-toml', '/tools/developer-tools/json-formatter'],
  '/tools/developer-tools/xml-formatter': ['/tools/developer-tools/xml-to-json', '/tools/developer-tools/json-to-xml', '/tools/developer-tools/html-formatter', '/tools/developer-tools/json-formatter', '/tools/developer-tools/code-formatter'],
  '/tools/developer-tools/xml-to-json': ['/tools/developer-tools/json-to-xml', '/tools/developer-tools/xml-formatter', '/tools/developer-tools/json-formatter', '/tools/developer-tools/yaml-to-json', '/tools/developer-tools/json-to-csv'],
  '/tools/developer-tools/yaml-to-json': ['/tools/developer-tools/json-to-yaml', '/tools/developer-tools/toml-to-json', '/tools/developer-tools/json-formatter', '/tools/developer-tools/xml-to-json', '/tools/developer-tools/code-formatter'],
  '/tools/developer-tools/toml-to-json': ['/tools/developer-tools/json-to-toml', '/tools/developer-tools/yaml-to-json', '/tools/developer-tools/json-formatter', '/tools/developer-tools/env-to-json', '/tools/developer-tools/json-to-yaml'],
  '/tools/developer-tools/csv-to-json': ['/tools/developer-tools/json-to-csv', '/tools/developer-tools/csv-to-excel', '/tools/developer-tools/csv-to-sql', '/tools/developer-tools/json-formatter', '/tools/developer-tools/excel-to-json', '/tools/developer-tools/csv-to-tsv'],
  '/tools/developer-tools/csv-to-excel': ['/tools/developer-tools/excel-to-csv', '/tools/developer-tools/csv-to-json', '/tools/developer-tools/csv-to-tsv', '/tools/pdf-tools/excel-to-pdf', '/tools/developer-tools/csv-to-sql'],
  '/tools/developer-tools/csv-to-sql': ['/tools/developer-tools/sql-to-csv', '/tools/developer-tools/csv-to-json', '/tools/developer-tools/csv-to-excel', '/tools/developer-tools/sql-formatter', '/tools/developer-tools/excel-to-csv'],
  '/tools/developer-tools/csv-to-tsv': ['/tools/developer-tools/tsv-to-csv', '/tools/developer-tools/csv-to-excel', '/tools/developer-tools/csv-to-json', '/tools/developer-tools/excel-to-csv', '/tools/developer-tools/csv-to-sql'],
  '/tools/developer-tools/excel-to-csv': ['/tools/developer-tools/csv-to-excel', '/tools/developer-tools/excel-to-json', '/tools/developer-tools/csv-to-json', '/tools/pdf-tools/pdf-to-excel', '/tools/developer-tools/csv-to-tsv', '/tools/pdf-tools/excel-to-pdf'],
  '/tools/developer-tools/excel-to-json': ['/tools/developer-tools/excel-to-csv', '/tools/developer-tools/json-to-csv', '/tools/developer-tools/csv-to-excel', '/tools/developer-tools/json-formatter', '/tools/developer-tools/csv-to-json'],
  '/tools/developer-tools/sql-to-csv': ['/tools/developer-tools/csv-to-sql', '/tools/developer-tools/sql-formatter', '/tools/developer-tools/csv-to-excel', '/tools/developer-tools/csv-to-json'],
  '/tools/developer-tools/tsv-to-csv': ['/tools/developer-tools/csv-to-tsv', '/tools/developer-tools/csv-to-json', '/tools/developer-tools/csv-to-excel', '/tools/developer-tools/excel-to-csv', '/tools/developer-tools/csv-to-sql'],
  '/tools/developer-tools/base64-encoder': ['/tools/file-tools/base64-encoder', '/tools/image-tools/image-to-base64', '/tools/developer-tools/url-encoder', '/tools/developer-tools/hex-to-text', '/tools/developer-tools/jwt-decoder', '/tools/developer-tools/hash-generator'],
  '/tools/developer-tools/url-encoder': ['/tools/developer-tools/url-parser', '/tools/developer-tools/base64-encoder', '/tools/developer-tools/html-encoder', '/tools/developer-tools/unicode-converter', '/tools/developer-tools/api-tester'],
  '/tools/developer-tools/url-parser': ['/tools/developer-tools/url-encoder', '/tools/developer-tools/api-tester', '/tools/developer-tools/regex-tester', '/tools/qr-barcodes-tools/qr-generator'],
  '/tools/developer-tools/html-formatter': ['/tools/developer-tools/html-encoder', '/tools/developer-tools/css-formatter', '/tools/developer-tools/javascript-formatter', '/tools/developer-tools/code-formatter', '/tools/developer-tools/markdown-to-html', '/tools/developer-tools/xml-formatter'],
  '/tools/developer-tools/html-encoder': ['/tools/developer-tools/html-entity-decoder', '/tools/developer-tools/url-encoder', '/tools/developer-tools/html-formatter', '/tools/developer-tools/unicode-converter', '/tools/developer-tools/base64-encoder'],
  '/tools/developer-tools/html-entity-decoder': ['/tools/developer-tools/html-encoder', '/tools/developer-tools/unicode-converter', '/tools/developer-tools/url-encoder', '/tools/developer-tools/html-formatter'],
  '/tools/developer-tools/css-formatter': ['/tools/developer-tools/scss-to-css', '/tools/developer-tools/html-formatter', '/tools/developer-tools/javascript-formatter', '/tools/developer-tools/code-minifier', '/tools/developer-tools/code-formatter'],
  '/tools/developer-tools/scss-to-css': ['/tools/developer-tools/css-formatter', '/tools/developer-tools/code-minifier', '/tools/developer-tools/code-formatter', '/tools/developer-tools/typescript-to-js'],
  '/tools/developer-tools/javascript-formatter': ['/tools/developer-tools/js-minifier', '/tools/developer-tools/code-formatter', '/tools/developer-tools/typescript-to-js', '/tools/developer-tools/css-formatter', '/tools/developer-tools/html-formatter', '/tools/developer-tools/json-formatter'],
  '/tools/developer-tools/js-minifier': ['/tools/developer-tools/javascript-formatter', '/tools/developer-tools/code-minifier', '/tools/developer-tools/typescript-to-js', '/tools/developer-tools/json-minifier', '/tools/developer-tools/css-formatter'],
  '/tools/developer-tools/typescript-to-js': ['/tools/developer-tools/javascript-formatter', '/tools/developer-tools/js-minifier', '/tools/developer-tools/json-to-typescript', '/tools/developer-tools/code-formatter', '/tools/developer-tools/scss-to-css'],
  '/tools/developer-tools/sql-formatter': ['/tools/developer-tools/csv-to-sql', '/tools/developer-tools/sql-to-csv', '/tools/developer-tools/code-formatter', '/tools/developer-tools/json-formatter'],
  '/tools/developer-tools/markdown-editor': ['/tools/developer-tools/markdown-previewer', '/tools/developer-tools/markdown-to-html', '/tools/pdf-tools/markdown-to-pdf', '/tools/developer-tools/html-formatter', '/tools/text-tools/word-counter'],
  '/tools/developer-tools/markdown-previewer': ['/tools/developer-tools/markdown-editor', '/tools/developer-tools/markdown-to-html', '/tools/pdf-tools/markdown-to-pdf', '/tools/developer-tools/html-formatter'],
  '/tools/developer-tools/markdown-to-html': ['/tools/pdf-tools/markdown-to-pdf', '/tools/developer-tools/markdown-editor', '/tools/developer-tools/html-formatter', '/tools/developer-tools/markdown-previewer', '/tools/pdf-tools/html-to-pdf'],
  '/tools/developer-tools/hash-generator': ['/tools/developer-tools/base64-encoder', '/tools/developer-tools/password-generator', '/tools/developer-tools/uuid-generator', '/tools/developer-tools/jwt-decoder', '/tools/file-tools/zip-extractor', '/tools/file-tools/file-comparator'],
  '/tools/developer-tools/uuid-generator': ['/tools/developer-tools/password-generator', '/tools/developer-tools/hash-generator', '/tools/developer-tools/timestamp-converter', '/tools/developer-tools/jwt-decoder'],
  '/tools/developer-tools/password-generator': ['/tools/developer-tools/hash-generator', '/tools/file-tools/file-encryptor', '/tools/text-tools/text-encryptor', '/tools/developer-tools/uuid-generator', '/tools/pdf-tools/pdf-protect'],
  '/tools/developer-tools/jwt-decoder': ['/tools/developer-tools/base64-encoder', '/tools/developer-tools/timestamp-converter', '/tools/developer-tools/json-formatter', '/tools/developer-tools/hash-generator', '/tools/developer-tools/api-tester'],
  '/tools/developer-tools/regex-tester': ['/tools/text-tools/find-replace', '/tools/text-tools/whitespace-remover', '/tools/developer-tools/url-parser', '/tools/developer-tools/javascript-formatter'],
  '/tools/developer-tools/diff-viewer': ['/tools/text-tools/text-comparator', '/tools/file-tools/file-comparator', '/tools/pdf-tools/pdf-compare', '/tools/developer-tools/code-formatter', '/tools/developer-tools/json-formatter'],
  '/tools/developer-tools/code-formatter': ['/tools/developer-tools/code-minifier', '/tools/developer-tools/javascript-formatter', '/tools/developer-tools/html-formatter', '/tools/developer-tools/css-formatter', '/tools/developer-tools/json-formatter', '/tools/developer-tools/sql-formatter'],
  '/tools/developer-tools/code-minifier': ['/tools/developer-tools/code-formatter', '/tools/developer-tools/js-minifier', '/tools/developer-tools/json-minifier', '/tools/developer-tools/css-formatter', '/tools/developer-tools/html-formatter'],
  '/tools/developer-tools/color-picker': ['/tools/converter-tools/color-converter', '/tools/developer-tools/css-formatter', '/tools/developer-tools/scss-to-css', '/tools/developer-tools/number-base-converter'],
  '/tools/developer-tools/aspect-ratio': ['/tools/image-tools/image-resizer', '/tools/video-tools/video-resizer', '/tools/image-tools/image-cropper', '/tools/math-tools/fraction-calculator'],
  '/tools/developer-tools/timestamp-converter': ['/tools/developer-tools/cron-expression', '/tools/developer-tools/jwt-decoder', '/tools/developer-tools/uuid-generator', '/tools/converter-tools/unit-converter'],
  '/tools/developer-tools/cron-expression': ['/tools/developer-tools/cron-expression-builder', '/tools/developer-tools/timestamp-converter', '/tools/developer-tools/env-to-json', '/tools/developer-tools/json-to-yaml'],
  '/tools/developer-tools/cron-expression-builder': ['/tools/developer-tools/cron-expression', '/tools/developer-tools/timestamp-converter', '/tools/developer-tools/env-to-json', '/tools/developer-tools/json-to-yaml'],
  '/tools/developer-tools/hex-to-text': ['/tools/developer-tools/number-base-converter', '/tools/developer-tools/unicode-converter', '/tools/developer-tools/base64-encoder', '/tools/developer-tools/url-encoder', '/tools/developer-tools/hash-generator'],
  '/tools/developer-tools/unicode-converter': ['/tools/developer-tools/hex-to-text', '/tools/developer-tools/html-entity-decoder', '/tools/developer-tools/url-encoder', '/tools/developer-tools/base64-encoder', '/tools/text-tools/character-counter'],
  '/tools/developer-tools/number-base-converter': ['/tools/developer-tools/hex-to-text', '/tools/math-tools/roman-numeral-converter', '/tools/developer-tools/unicode-converter', '/tools/converter-tools/color-converter', '/tools/math-tools/scientific-calculator'],
  '/tools/developer-tools/env-to-json': ['/tools/developer-tools/json-formatter', '/tools/developer-tools/json-to-yaml', '/tools/developer-tools/yaml-to-json', '/tools/developer-tools/toml-to-json', '/tools/developer-tools/json-to-toml'],
  '/tools/developer-tools/api-tester': ['/tools/developer-tools/json-formatter', '/tools/developer-tools/jwt-decoder', '/tools/developer-tools/url-parser', '/tools/developer-tools/url-encoder', '/tools/developer-tools/base64-encoder'],
  // math-tools
  '/tools/math-tools/scientific-calculator': ['/tools/math-tools/fraction-calculator', '/tools/math-tools/percentage-calculator', '/tools/math-tools/statistics-calculator', '/tools/math-tools/number-base-converter', '/tools/converter-tools/unit-converter'],
  '/tools/math-tools/percentage-calculator': ['/tools/math-tools/fraction-calculator', '/tools/math-tools/statistics-calculator', '/tools/math-tools/scientific-calculator', '/tools/converter-tools/currency-converter', '/tools/converter-tools/unit-converter'],
  '/tools/math-tools/fraction-calculator': ['/tools/math-tools/percentage-calculator', '/tools/math-tools/scientific-calculator', '/tools/math-tools/statistics-calculator', '/tools/developer-tools/aspect-ratio'],
  '/tools/math-tools/statistics-calculator': ['/tools/math-tools/percentage-calculator', '/tools/math-tools/scientific-calculator', '/tools/math-tools/fraction-calculator', '/tools/text-tools/text-sorter'],
  '/tools/math-tools/roman-numeral-converter': ['/tools/math-tools/number-base-converter', '/tools/math-tools/scientific-calculator', '/tools/converter-tools/unit-converter', '/tools/math-tools/fraction-calculator'],
  '/tools/math-tools/number-base-converter': ['/tools/math-tools/scientific-calculator', '/tools/math-tools/roman-numeral-converter', '/tools/developer-tools/hex-to-text', '/tools/converter-tools/color-converter'],
  // ai-tools
  '/tools/ai-tools/ai-chatbot': ['/tools/ai-tools/ai-writer', '/tools/ai-tools/text-summarizer', '/tools/ai-tools/ai-translator', '/tools/ai-tools/grammar-fixer', '/tools/ai-tools/email-generator'],
  '/tools/ai-tools/ai-translator': ['/tools/pdf-tools/pdf-translate', '/tools/ai-tools/grammar-fixer', '/tools/ai-tools/ai-paraphraser', '/tools/ai-tools/text-summarizer', '/tools/ai-tools/audio-transcriber'],
  '/tools/ai-tools/ai-writer': ['/tools/ai-tools/ai-paraphraser', '/tools/ai-tools/grammar-fixer', '/tools/ai-tools/email-generator', '/tools/ai-tools/ai-detector', '/tools/text-tools/word-counter', '/tools/ai-tools/ai-chatbot'],
  '/tools/ai-tools/ai-detector': ['/tools/ai-tools/ai-paraphraser', '/tools/ai-tools/ai-writer', '/tools/ai-tools/grammar-fixer', '/tools/text-tools/word-counter'],
  '/tools/ai-tools/ai-paraphraser': ['/tools/ai-tools/grammar-fixer', '/tools/ai-tools/ai-writer', '/tools/ai-tools/ai-detector', '/tools/ai-tools/text-summarizer', '/tools/ai-tools/ai-translator'],
  '/tools/ai-tools/grammar-fixer': ['/tools/ai-tools/ai-paraphraser', '/tools/ai-tools/ai-writer', '/tools/text-tools/word-counter', '/tools/ai-tools/ai-translator', '/tools/ai-tools/email-generator'],
  '/tools/ai-tools/text-summarizer': ['/tools/pdf-tools/pdf-ai-summary', '/tools/ai-tools/keyword-extractor', '/tools/ai-tools/ai-paraphraser', '/tools/text-tools/word-counter', '/tools/ai-tools/audio-transcriber'],
  '/tools/ai-tools/background-remover': ['/tools/ai-tools/image-upscaler', '/tools/image-tools/image-editor', '/tools/image-tools/image-cropper', '/tools/image-tools/jpg-to-png', '/tools/image-tools/image-compressor'],
  '/tools/ai-tools/image-upscaler': ['/tools/image-tools/image-resizer', '/tools/ai-tools/background-remover', '/tools/image-tools/image-compressor', '/tools/ai-tools/image-generator', '/tools/image-tools/image-editor'],
  '/tools/ai-tools/image-generator': ['/tools/ai-tools/image-upscaler', '/tools/ai-tools/image-captioner', '/tools/ai-tools/background-remover', '/tools/image-tools/image-editor', '/tools/image-tools/image-compressor'],
  '/tools/ai-tools/image-captioner': ['/tools/ai-tools/image-generator', '/tools/image-tools/image-metadata', '/tools/ai-tools/keyword-extractor', '/tools/ai-tools/ai-writer'],
  '/tools/ai-tools/audio-transcriber': ['/tools/audio-tools/audio-to-text', '/tools/video-tools/video-to-audio', '/tools/video-tools/subtitle-generator', '/tools/ai-tools/text-summarizer', '/tools/ai-tools/ai-translator', '/tools/audio-tools/voice-recorder'],
  '/tools/ai-tools/email-generator': ['/tools/ai-tools/ai-writer', '/tools/ai-tools/grammar-fixer', '/tools/ai-tools/ai-paraphraser', '/tools/ai-tools/ai-translator', '/tools/ai-tools/sentiment-analyzer'],
  '/tools/ai-tools/keyword-extractor': ['/tools/ai-tools/text-summarizer', '/tools/ai-tools/sentiment-analyzer', '/tools/ai-tools/data-extractor', '/tools/text-tools/word-counter', '/tools/ai-tools/ai-writer'],
  '/tools/ai-tools/sentiment-analyzer': ['/tools/ai-tools/keyword-extractor', '/tools/ai-tools/text-summarizer', '/tools/ai-tools/ai-detector', '/tools/ai-tools/data-extractor', '/tools/ai-tools/email-generator'],
  '/tools/ai-tools/data-extractor': ['/tools/ai-tools/keyword-extractor', '/tools/pdf-tools/pdf-extract-text', '/tools/pdf-tools/pdf-to-excel', '/tools/developer-tools/json-formatter', '/tools/developer-tools/json-to-csv', '/tools/ai-tools/text-summarizer'],
};

// The visible name of each tool (its page's <h1>, as a visitor sees it), for every
// tool on disk.
export const TOOL_NAMES = {
  '/tools/pdf-tools/pdf-merge': 'Merge PDF',
  '/tools/pdf-tools/pdf-split': 'Split PDF',
  '/tools/pdf-tools/pdf-compress': 'PDF Compression',
  '/tools/pdf-tools/pdf-to-word': 'PDF to Word',
  '/tools/pdf-tools/pdf-to-excel': 'PDF to Excel',
  '/tools/pdf-tools/pdf-to-jpg': 'PDF to JPG',
  '/tools/pdf-tools/pdf-to-image': 'PDF to Image',
  '/tools/pdf-tools/pdf-to-html': 'PDF to HTML',
  '/tools/pdf-tools/pdf-to-ppt': 'PDF to PowerPoint',
  '/tools/pdf-tools/pdf-to-pdfa': 'PDF to PDF/A',
  '/tools/pdf-tools/word-to-pdf': 'Word to PDF',
  '/tools/pdf-tools/jpg-to-pdf': 'JPG to PDF',
  '/tools/pdf-tools/image-to-pdf': 'Image to PDF',
  '/tools/pdf-tools/excel-to-pdf': 'Excel to PDF',
  '/tools/pdf-tools/ppt-to-pdf': 'PowerPoint to PDF',
  '/tools/pdf-tools/html-to-pdf': 'HTML to PDF',
  '/tools/pdf-tools/epub-to-pdf': 'EPUB to PDF',
  '/tools/pdf-tools/mobi-to-pdf': 'MOBI to PDF',
  '/tools/pdf-tools/markdown-to-pdf': 'Markdown to PDF',
  '/tools/pdf-tools/text-to-pdf': 'Text to PDF',
  '/tools/pdf-tools/pdf-sign': 'Sign PDF',
  '/tools/pdf-tools/pdf-editor': 'PDF Editor',
  '/tools/pdf-tools/pdf-ocr': 'PDF OCR',
  '/tools/pdf-tools/pdf-forms': 'PDF Forms',
  '/tools/pdf-tools/pdf-protect': 'Protect PDF',
  '/tools/pdf-tools/pdf-unlock': 'Unlock PDF',
  '/tools/pdf-tools/pdf-watermark': 'PDF Watermark',
  '/tools/pdf-tools/pdf-rotate': 'Rotate PDF Pages',
  '/tools/pdf-tools/pdf-crop': 'Crop PDF',
  '/tools/pdf-tools/pdf-repair': 'PDF Repair',
  '/tools/pdf-tools/pdf-compare': 'Compare PDF',
  '/tools/pdf-tools/pdf-redact': 'Redact PDF',
  '/tools/pdf-tools/pdf-translate': 'Translate PDF',
  '/tools/pdf-tools/pdf-organize': 'Organize PDF',
  '/tools/pdf-tools/pdf-reorder-pages': 'Reorder PDF Pages',
  '/tools/pdf-tools/pdf-delete-pages': 'Delete PDF Pages',
  '/tools/pdf-tools/pdf-number-pages': 'Number PDF Pages',
  '/tools/pdf-tools/pdf-extract-text': 'Extract Text from PDF',
  '/tools/pdf-tools/pdf-ai-summary': 'AI PDF Summary',
  '/tools/image-tools/image-compressor': 'Image Compressor',
  '/tools/image-tools/image-converter': 'Image Converter',
  '/tools/image-tools/image-resizer': 'Image Resizer',
  '/tools/image-tools/image-cropper': 'Image Cropper',
  '/tools/image-tools/image-editor': 'Image Editor',
  '/tools/image-tools/image-flip': 'Image Flip',
  '/tools/image-tools/image-rotate': 'Image Rotate',
  '/tools/image-tools/image-blur': 'Image Blur',
  '/tools/image-tools/image-inverter': 'Image Inverter',
  '/tools/image-tools/image-pixelator': 'Image Pixelator',
  '/tools/image-tools/image-comparison': 'Image Comparison',
  '/tools/image-tools/image-metadata': 'Image Metadata Viewer',
  '/tools/image-tools/image-to-base64': 'Image to Base64',
  '/tools/image-tools/add-border-to-image': 'Add Border to Image',
  '/tools/image-tools/add-text-to-image': 'Add Text to Image',
  '/tools/image-tools/add-noise': 'Add Noise',
  '/tools/image-tools/add-vignette': 'Add Vignette',
  '/tools/image-tools/brightness-contrast': 'Brightness and Contrast',
  '/tools/image-tools/grayscale-converter': 'Grayscale Converter',
  '/tools/image-tools/sepia-filter': 'Sepia Filter',
  '/tools/image-tools/round-corners': 'Round Corners',
  '/tools/image-tools/duplicate-image-finder': 'Duplicate Image Finder',
  '/tools/image-tools/jpg-to-png': 'JPG to PNG',
  '/tools/image-tools/jpg-to-webp': 'JPG to WebP',
  '/tools/image-tools/png-to-jpg': 'PNG to JPG',
  '/tools/image-tools/png-to-webp': 'PNG to WebP',
  '/tools/image-tools/png-to-ico': 'PNG to ICO',
  '/tools/image-tools/webp-to-jpg': 'WebP to JPG',
  '/tools/image-tools/webp-to-png': 'WebP to PNG',
  '/tools/image-tools/bmp-to-png': 'BMP to PNG',
  '/tools/image-tools/svg-to-png': 'SVG to PNG',
  '/tools/image-tools/heic-to-jpg': 'HEIC to JPG',
  '/tools/image-tools/heic-to-png': 'HEIC to PNG',
  '/tools/image-tools/ico-to-png': 'ICO to PNG',
  '/tools/image-tools/tiff-to-jpg': 'TIFF to JPG',
  '/tools/image-tools/tiff-to-png': 'TIFF to PNG',
  '/tools/image-tools/gif-to-png': 'GIF to PNG',
  '/tools/gif-tools/apng-to-gif': 'APNG to GIF',
  '/tools/gif-tools/avi-to-gif': 'AVI to GIF',
  '/tools/gif-tools/mov-to-gif': 'MOV to GIF',
  '/tools/gif-tools/mp4-to-gif': 'MP4 to GIF',
  '/tools/gif-tools/webm-to-gif': 'WebM to GIF',
  '/tools/gif-tools/video-to-gif': 'Video to GIF',
  '/tools/gif-tools/gif-to-mp4': 'GIF to MP4',
  '/tools/gif-tools/gif-to-apng': 'GIF to APNG',
  '/tools/gif-tools/image-to-gif': 'Image to GIF',
  '/tools/gif-tools/gif-maker': 'GIF Maker',
  '/tools/gif-tools/gif-compressor': 'GIF Compressor',
  '/tools/audio-tools/audio-converter': 'Audio Converter',
  '/tools/audio-tools/audio-compressor': 'Audio Compressor',
  '/tools/audio-tools/audio-trimmer': 'Audio Trimmer',
  '/tools/audio-tools/audio-merger': 'Audio Merger',
  '/tools/audio-tools/audio-splitter': 'Audio Splitter',
  '/tools/audio-tools/audio-booster': 'Audio Booster',
  '/tools/audio-tools/audio-equalizer': 'Audio Equalizer',
  '/tools/audio-tools/audio-metadata': 'Audio Metadata',
  '/tools/audio-tools/audio-waveform': 'Audio Waveform',
  '/tools/audio-tools/audio-to-text': 'Audio to Text',
  '/tools/audio-tools/voice-recorder': 'Voice Recorder',
  '/tools/video-tools/video-converter': 'Video Converter',
  '/tools/video-tools/video-compressor': 'Video Compressor',
  '/tools/video-tools/video-trimmer': 'Video Trimmer',
  '/tools/video-tools/video-merger': 'Video Merger',
  '/tools/video-tools/video-resizer': 'Video Resizer',
  '/tools/video-tools/video-rotator': 'Video Rotator',
  '/tools/video-tools/video-filter': 'Video Filter',
  '/tools/video-tools/video-watermark': 'Video Watermark',
  '/tools/video-tools/video-metadata': 'Video Metadata',
  '/tools/video-tools/video-screenshot': 'Video Screenshot',
  '/tools/video-tools/video-to-audio': 'Video to Audio',
  '/tools/video-tools/video-to-gif': 'Video to GIF',
  '/tools/video-tools/media-player': 'Media Player',
  '/tools/video-tools/screen-recorder': 'Screen Recorder',
  '/tools/video-tools/subtitle-generator': 'Subtitle Generator',
  '/tools/text-tools/word-counter': 'Word Counter',
  '/tools/text-tools/character-counter': 'Character Counter',
  '/tools/text-tools/case-converter': 'Case Converter',
  '/tools/text-tools/text-reverser': 'Text Reverser',
  '/tools/text-tools/text-sorter': 'Text Sorter',
  '/tools/text-tools/text-comparator': 'Text Comparator',
  '/tools/text-tools/text-repeater': 'Text Repeater',
  '/tools/text-tools/text-truncator': 'Text Truncator',
  '/tools/text-tools/text-encryptor': 'Text Encryptor',
  '/tools/text-tools/text-to-list': 'Text to List',
  '/tools/text-tools/find-replace': 'Find and Replace',
  '/tools/text-tools/duplicate-remover': 'Duplicate Remover',
  '/tools/text-tools/whitespace-remover': 'Whitespace Remover',
  '/tools/text-tools/lorem-ipsum': 'Lorem Ipsum Generator',
  '/tools/text-tools/ascii-art': 'ASCII Art Generator',
  '/tools/text-tools/sticky-notes': 'Sticky Notes',
  '/tools/text-tools/url-encoder': 'URL Encoder',
  '/tools/file-tools/zip-creator': 'ZIP Creator',
  '/tools/file-tools/zip-extractor': 'ZIP Extractor',
  '/tools/file-tools/tar-extractor': 'TAR Extractor',
  '/tools/file-tools/file-converter': 'File Converter',
  '/tools/file-tools/file-comparator': 'File Comparator',
  '/tools/file-tools/file-encryptor': 'File Encryptor',
  '/tools/file-tools/file-metadata': 'File Metadata',
  '/tools/file-tools/file-splitter': 'File Splitter',
  '/tools/file-tools/base64-encoder': 'File to Base64',
  '/tools/qr-barcodes-tools/qr-generator': 'QR Code Generator',
  '/tools/qr-barcodes-tools/qr-scanner': 'QR Code Scanner',
  '/tools/qr-barcodes-tools/barcode-generator': 'Barcode Generator',
  '/tools/converter-tools/color-converter': 'Color Converter',
  '/tools/converter-tools/currency-converter': 'Currency Converter',
  '/tools/converter-tools/unit-converter': 'Unit Converter',
  '/tools/converter-tools/mobi-to-epub': 'MOBI to EPUB',
  '/tools/developer-tools/json-formatter': 'JSON Formatter',
  '/tools/developer-tools/json-minifier': 'JSON Minifier',
  '/tools/developer-tools/json-to-csv': 'JSON to CSV',
  '/tools/developer-tools/json-to-xml': 'JSON to XML',
  '/tools/developer-tools/json-to-yaml': 'JSON to YAML',
  '/tools/developer-tools/json-to-toml': 'JSON to TOML',
  '/tools/developer-tools/json-to-typescript': 'JSON to TypeScript',
  '/tools/developer-tools/json-to-python': 'JSON to Python Class',
  '/tools/developer-tools/json-to-go': 'JSON to Go Struct',
  '/tools/developer-tools/json-to-php': 'JSON to PHP Class',
  '/tools/developer-tools/json-to-csharp': 'JSON to C# Class',
  '/tools/developer-tools/json-to-rust': 'JSON to Rust Struct',
  '/tools/developer-tools/xml-formatter': 'XML Formatter',
  '/tools/developer-tools/xml-to-json': 'XML to JSON',
  '/tools/developer-tools/yaml-to-json': 'YAML to JSON',
  '/tools/developer-tools/toml-to-json': 'TOML to JSON',
  '/tools/developer-tools/csv-to-json': 'CSV to JSON',
  '/tools/developer-tools/csv-to-excel': 'CSV to Excel',
  '/tools/developer-tools/csv-to-sql': 'CSV to SQL',
  '/tools/developer-tools/csv-to-tsv': 'CSV to TSV',
  '/tools/developer-tools/excel-to-csv': 'Excel to CSV',
  '/tools/developer-tools/excel-to-json': 'Excel to JSON',
  '/tools/developer-tools/sql-to-csv': 'SQL to CSV',
  '/tools/developer-tools/tsv-to-csv': 'TSV to CSV',
  '/tools/developer-tools/base64-encoder': 'Base64 Encoder',
  '/tools/developer-tools/url-encoder': 'URL Encoder',
  '/tools/developer-tools/url-parser': 'URL Parser',
  '/tools/developer-tools/html-formatter': 'HTML Formatter',
  '/tools/developer-tools/html-encoder': 'HTML Encoder',
  '/tools/developer-tools/html-entity-decoder': 'HTML Entity Decoder',
  '/tools/developer-tools/css-formatter': 'CSS Formatter',
  '/tools/developer-tools/scss-to-css': 'SCSS to CSS',
  '/tools/developer-tools/javascript-formatter': 'JavaScript Formatter',
  '/tools/developer-tools/js-minifier': 'JS Minifier',
  '/tools/developer-tools/typescript-to-js': 'TypeScript to JavaScript',
  '/tools/developer-tools/sql-formatter': 'SQL Formatter',
  '/tools/developer-tools/markdown-editor': 'Markdown Editor',
  '/tools/developer-tools/markdown-previewer': 'Markdown Previewer',
  '/tools/developer-tools/markdown-to-html': 'Markdown to HTML',
  '/tools/developer-tools/hash-generator': 'Hash Generator',
  '/tools/developer-tools/uuid-generator': 'UUID Generator',
  '/tools/developer-tools/password-generator': 'Password Generator',
  '/tools/developer-tools/jwt-decoder': 'JWT Decoder',
  '/tools/developer-tools/regex-tester': 'Regex Tester',
  '/tools/developer-tools/diff-viewer': 'Diff Viewer',
  '/tools/developer-tools/code-formatter': 'Code Formatter',
  '/tools/developer-tools/code-minifier': 'Code Minifier',
  '/tools/developer-tools/color-picker': 'Color Picker',
  '/tools/developer-tools/aspect-ratio': 'Aspect Ratio Calculator',
  '/tools/developer-tools/timestamp-converter': 'Timestamp Converter',
  '/tools/developer-tools/cron-expression': 'Cron Expression',
  '/tools/developer-tools/cron-expression-builder': 'Cron Expression Builder',
  '/tools/developer-tools/hex-to-text': 'Hex to Text',
  '/tools/developer-tools/unicode-converter': 'Unicode Converter',
  '/tools/developer-tools/number-base-converter': 'Number Base Converter',
  '/tools/developer-tools/env-to-json': '.env to JSON',
  '/tools/developer-tools/api-tester': 'API Tester',
  '/tools/math-tools/scientific-calculator': 'Scientific Calculator',
  '/tools/math-tools/percentage-calculator': 'Percentage Calculator',
  '/tools/math-tools/fraction-calculator': 'Fraction Calculator',
  '/tools/math-tools/statistics-calculator': 'Statistics Calculator',
  '/tools/math-tools/roman-numeral-converter': 'Roman Numeral Converter',
  '/tools/math-tools/number-base-converter': 'Number Base Converter',
  '/tools/ai-tools/ai-chatbot': 'AI Chatbot',
  '/tools/ai-tools/ai-translator': 'AI Translator',
  '/tools/ai-tools/ai-writer': 'AI Writer',
  '/tools/ai-tools/ai-detector': 'AI Detector',
  '/tools/ai-tools/ai-paraphraser': 'AI Paraphraser',
  '/tools/ai-tools/grammar-fixer': 'Grammar Fixer',
  '/tools/ai-tools/text-summarizer': 'Text Summarizer',
  '/tools/ai-tools/background-remover': 'Background Remover',
  '/tools/ai-tools/image-upscaler': 'AI Image Upscaler',
  '/tools/ai-tools/image-generator': 'AI Image Generator',
  '/tools/ai-tools/image-captioner': 'Image Captioner',
  '/tools/ai-tools/audio-transcriber': 'Audio Transcriber',
  '/tools/ai-tools/email-generator': 'Email Generator',
  '/tools/ai-tools/keyword-extractor': 'Keyword Extractor',
  '/tools/ai-tools/sentiment-analyzer': 'Sentiment Analyzer',
  '/tools/ai-tools/data-extractor': 'Data Extractor',
};
