import { createElement } from 'react';
import {
  Combine, Scissors, FileArchive, Lock, Unlock, RotateCw, Droplet, Image,
  FileText, FileEdit, FileSpreadsheet, Table, Presentation, MonitorPlay, Code2,
  FileType, FileCode, BookOpen, Book, Globe, Trash2, ArrowDownUp, FolderKanban, FileSearch,
  Hash, PenSquare, PenLine, ScanSearch, ClipboardList, EyeOff, Crop, GitCompare, Archive,
  Wrench, Sparkles, Languages, Minimize2, RefreshCw, Maximize2, FlipHorizontal, Squircle, Type,
  SlidersHorizontal, Frame, Columns2, Copy, Contrast, Eclipse, Droplets, Blend, Palette, Info,
  Grid3x3, Sparkle, CircleDot, Smartphone, PenTool, AppWindow,
  Layers, Film, Camera, Component, Binary, Clapperboard, Video, Wand2, Sticker, CaseSensitive,
  ArrowDownAZ, Replace, Eraser, Link2, ListChecks, Repeat, Shuffle, Calculator, Terminal, StickyNote,
  Split, Volume2, Mic, Captions, AudioWaveform, Music, PlayCircle, FolderOpen, FolderArchive,
  QrCode, ScanLine, Barcode, Coins, Ruler, Code, Braces, Table2, FileCode2, Settings2,
  Fingerprint, KeyRound, ArrowRightLeft, ArrowLeftRight, Database, Regex, Eye, Webhook, Pipette,
  Clock, RectangleHorizontal, Link, CodeXml, FileType2, Boxes, Cog, Server, AtSign, Settings,
  Timer, ShieldCheck, Percent, Divide, BarChart3, Expand, SpellCheck, MessageCircle, ShieldAlert,
  Smile, Tag, Tags, Mail, Folder, Bot, LayoutGrid, Cloud, Zap, AlignLeft, Pilcrow,
} from 'lucide-react';

// Single source of truth for every tool + category icon on the site.
// Keyed by the last URL segment (tool slug) or category slug.
// Replaces the emoji maps previously duplicated across 15 files.
export const toolIcons = {
  // PDF Tools
  'pdf-merge': Combine, 'pdf-split': Scissors, 'pdf-compress': FileArchive,
  'pdf-protect': Lock, 'pdf-unlock': Unlock, 'pdf-rotate': RotateCw, 'pdf-watermark': Droplet,
  'image-to-pdf': ArrowRightLeft, 'pdf-to-image': ArrowRightLeft, 'pdf-to-jpg': ArrowRightLeft, 'jpg-to-pdf': ArrowRightLeft,
  'word-to-pdf': FileText, 'pdf-to-word': FileEdit, 'excel-to-pdf': FileSpreadsheet,
  'pdf-to-excel': FileSpreadsheet, 'pdf-to-ppt': Presentation, 'ppt-to-pdf': MonitorPlay,
  'html-to-pdf': Code2, 'text-to-pdf': FileType, 'markdown-to-pdf': FileCode,
  'epub-to-pdf': BookOpen, 'mobi-to-pdf': Book, 'pdf-to-html': Globe,
  'pdf-delete-pages': Trash2, 'pdf-reorder-pages': ArrowDownUp, 'pdf-organize': FolderKanban,
  'pdf-extract-text': FileSearch, 'pdf-number-pages': Hash, 'pdf-editor': PenSquare,
  'pdf-sign': PenLine, 'pdf-ocr': ScanSearch, 'pdf-forms': ClipboardList, 'pdf-redact': EyeOff,
  'pdf-crop': Crop, 'pdf-compare': GitCompare, 'pdf-to-pdfa': Archive, 'pdf-repair': Wrench,
  'pdf-ai-summary': Sparkles, 'pdf-translate': Languages,

  // Image Tools
  'image-compressor': Minimize2, 'image-converter': RefreshCw, 'image-resizer': Maximize2,
  'image-cropper': Crop, 'image-rotate': RotateCw, 'image-flip': FlipHorizontal,
  'round-corners': Squircle, 'add-text-to-image': Type, 'image-editor': SlidersHorizontal,
  'add-border-to-image': Frame, 'brightness-contrast': Contrast, 'image-comparison': Columns2,
  'duplicate-image-finder': Copy, 'grayscale-converter': Eclipse, 'image-blur': Droplets,
  'image-inverter': Blend, 'sepia-filter': Palette, 'image-metadata': Info,
  'image-pixelator': Grid3x3, 'add-noise': Sparkle, 'add-vignette': CircleDot,
  'heic-to-jpg': Smartphone, 'heic-to-png': ArrowRightLeft, 'webp-to-png': ArrowRightLeft,
  'webp-to-jpg': ArrowRightLeft, 'png-to-jpg': ArrowRightLeft, 'jpg-to-png': ArrowRightLeft, 'svg-to-png': PenTool,
  'png-to-ico': AppWindow, 'jpg-to-webp': Globe, 'png-to-webp': Layers, 'gif-to-png': Film,
  'bmp-to-png': ArrowRightLeft, 'tiff-to-png': ArrowRightLeft, 'tiff-to-jpg': Camera, 'ico-to-png': Component,
  'image-to-base64': Binary,

  // GIF Tools
  'video-to-gif': ArrowRightLeft, 'mp4-to-gif': ArrowRightLeft, 'webm-to-gif': ArrowRightLeft, 'apng-to-gif': ArrowRightLeft,
  'gif-to-mp4': ArrowRightLeft, 'gif-to-apng': ArrowRightLeft, 'image-to-gif': ArrowRightLeft,
  'mov-to-gif': ArrowRightLeft, 'avi-to-gif': ArrowRightLeft, 'gif-maker': Sticker, 'gif-compressor': Minimize2,

  // Text Tools
  'word-counter': Hash, 'case-converter': CaseSensitive, 'text-reverser': FlipHorizontal,
  'duplicate-remover': Trash2, 'text-sorter': ArrowDownAZ, 'find-replace': Replace,
  'text-comparator': GitCompare, 'whitespace-remover': Eraser, 'lorem-ipsum': Pilcrow,
  'url-encoder': Link2, 'text-to-list': ListChecks, 'text-truncator': Scissors,
  'text-repeater': Repeat, 'character-counter': Ruler, 'text-encryptor': Lock,
  'ascii-art': Terminal, 'sticky-notes': StickyNote,

  // Audio Tools
  'audio-converter': RefreshCw, 'audio-trimmer': Scissors, 'audio-compressor': Minimize2,
  'audio-merger': Combine, 'audio-splitter': Split, 'audio-booster': Volume2,
  'audio-equalizer': SlidersHorizontal, 'audio-waveform': AudioWaveform, 'audio-metadata': Info,
  'voice-recorder': Mic, 'audio-to-text': Captions,

  // Video Tools
  'video-to-audio': Music, 'video-compressor': Minimize2, 'video-converter': RefreshCw,
  'video-trimmer': Scissors, 'video-screenshot': Camera, 'media-player': PlayCircle,
  'video-metadata': Info, 'video-watermark': Droplet, 'subtitle-generator': Captions,
  'screen-recorder': MonitorPlay, 'video-merger': Combine, 'video-rotator': RotateCw,
  'video-resizer': Maximize2, 'video-filter': SlidersHorizontal,

  // File Tools
  'zip-extractor': FolderOpen, 'zip-creator': FolderArchive, 'tar-extractor': Archive,
  'file-converter': RefreshCw, 'file-encryptor': Lock, 'file-metadata': Info,
  'base64-encoder': Binary, 'file-comparator': GitCompare, 'file-splitter': Split,

  // QR & Barcodes
  'qr-generator': QrCode, 'qr-scanner': ScanLine, 'barcode-generator': Barcode,

  // Converter Tools
  'currency-converter': Coins, 'unit-converter': Ruler, 'color-converter': Palette,
  'mobi-to-epub': BookOpen,

  // Developer Tools
  'xml-to-json': Code, 'json-to-xml': Braces, 'tsv-to-csv': Table2, 'csv-to-tsv': Table,
  'excel-to-json': FileSpreadsheet, 'excel-to-csv': Grid3x3, 'csv-to-excel': FileSpreadsheet,
  'toml-to-json': FileCode2, 'json-to-toml': Settings2, 'json-formatter': Braces,
  'json-minifier': Minimize2, 'uuid-generator': Fingerprint, 'hash-generator': Hash,
  'password-generator': KeyRound, 'csv-to-json': ArrowRightLeft, 'json-to-csv': ArrowLeftRight,
  'css-formatter': Layers, 'html-formatter': Code2, 'js-minifier': Minimize2,
  'javascript-formatter': Braces, 'scss-to-css': Layers, 'typescript-to-js': FileCode,
  'xml-formatter': Code, 'sql-formatter': Database, 'regex-tester': Regex,
  'markdown-previewer': Eye, 'markdown-to-html': FileCode2, 'jwt-decoder': ShieldCheck,
  'markdown-editor': FileEdit, 'api-tester': Webhook, 'number-base-converter': Binary,
  'yaml-to-json': FileCode2, 'json-to-yaml': FileCode2, 'color-picker': Pipette,
  'timestamp-converter': Clock, 'aspect-ratio': RectangleHorizontal, 'url-parser': Link,
  'html-encoder': Code, 'html-entity-decoder': CodeXml, 'unicode-converter': Type,
  'hex-to-text': Binary, 'json-to-typescript': FileType2, 'json-to-go': Boxes,
  'json-to-rust': Cog, 'json-to-python': Terminal, 'json-to-php': Server,
  'json-to-csharp': AtSign, 'csv-to-sql': Database, 'sql-to-csv': Table, 'env-to-json': Settings,
  'code-minifier': Minimize2, 'diff-viewer': GitCompare, 'code-formatter': Sparkles,
  'cron-expression': Timer, 'cron-expression-builder': Timer,

  // Math Tools
  'percentage-calculator': Percent, 'roman-numeral-converter': ArrowRightLeft,
  'scientific-calculator': Calculator, 'fraction-calculator': Divide,
  'statistics-calculator': BarChart3,

  // AI Tools
  'background-remover': Eraser, 'image-upscaler': Expand, 'grammar-fixer': SpellCheck,
  'text-summarizer': AlignLeft, 'ai-translator': Languages, 'image-generator': Wand2,
  'ai-chatbot': MessageCircle, 'ai-writer': PenLine, 'ai-detector': ShieldAlert,
  'audio-transcriber': Captions, 'sentiment-analyzer': Smile, 'image-captioner': Tag,
  'data-extractor': Database, 'ai-paraphraser': Shuffle, 'email-generator': Mail,
  'keyword-extractor': Tags,
};

export const categoryIcons = {
  'pdf-tools': FileText,
  'image-tools': Image,
  'gif-tools': Clapperboard,
  'text-tools': Type,
  'audio-tools': Music,
  'video-tools': Video,
  'file-tools': Folder,
  'qr-barcodes-tools': QrCode,
  'converter-tools': RefreshCw,
  'developer-tools': Code2,
  'math-tools': Calculator,
  'ai-tools': Bot,
};

// One accent color per category, shared by the homepage category cards and
// the navbar category icons so the two stay visually in sync.
export const categoryColors = {
  'pdf-tools': 'text-red-500',
  'image-tools': 'text-pink-500',
  'gif-tools': 'text-purple-500',
  'text-tools': 'text-green-500',
  'audio-tools': 'text-yellow-500',
  'video-tools': 'text-blue-500',
  'file-tools': 'text-orange-500',
  'qr-barcodes-tools': 'text-teal-500',
  'converter-tools': 'text-amber-500',
  'developer-tools': 'text-violet-500',
  'math-tools': 'text-indigo-500',
  'ai-tools': 'text-cyan-500',
};

// Fallback for any slug not (yet) mapped above.
export const DefaultToolIcon = FileText;

export function getToolIcon(slug) {
  return toolIcons[slug] || DefaultToolIcon;
}

export function getCategoryIcon(slug) {
  return categoryIcons[slug] || DefaultToolIcon;
}

// Per-tool color, one distinct hue+shade per tool with zero repetition within
// any single category page (grid cards, mega-menu badges, and the tool's own
// title icon all read from these two maps). Generated from each category's
// own tools array order; a shared href (e.g. Lorem Ipsum listed on both Text
// Tools and Developer Tools) keeps the color from its first assignment,
// reserved so it can never collide with another color on the second listing
// either. 17 Tailwind hue families x 4 shades (500/600/400/700, yellow
// restricted to 600/700 for contrast) = 66 combinations, comfortably above
// the largest category (Developer Tools, 58 tools).
export const toolTextColors = {
  '/tools/ai-tools/ai-chatbot': 'text-teal-500',
  '/tools/ai-tools/ai-detector': 'text-sky-500',
  '/tools/ai-tools/ai-paraphraser': 'text-fuchsia-500',
  '/tools/ai-tools/ai-translator': 'text-green-500',
  '/tools/ai-tools/ai-writer': 'text-cyan-500',
  '/tools/ai-tools/audio-transcriber': 'text-blue-500',
  '/tools/ai-tools/background-remover': 'text-red-500',
  '/tools/ai-tools/data-extractor': 'text-purple-500',
  '/tools/ai-tools/email-generator': 'text-pink-500',
  '/tools/ai-tools/grammar-fixer': 'text-amber-500',
  '/tools/ai-tools/image-captioner': 'text-violet-500',
  '/tools/ai-tools/image-generator': 'text-emerald-500',
  '/tools/ai-tools/image-upscaler': 'text-orange-500',
  '/tools/ai-tools/keyword-extractor': 'text-rose-500',
  '/tools/ai-tools/sentiment-analyzer': 'text-indigo-500',
  '/tools/ai-tools/text-summarizer': 'text-lime-500',
  '/tools/audio-tools/audio-booster': 'text-emerald-500',
  '/tools/audio-tools/audio-compressor': 'text-amber-500',
  '/tools/audio-tools/audio-converter': 'text-red-500',
  '/tools/audio-tools/audio-equalizer': 'text-teal-500',
  '/tools/audio-tools/audio-merger': 'text-lime-500',
  '/tools/audio-tools/audio-metadata': 'text-sky-500',
  '/tools/audio-tools/audio-splitter': 'text-green-500',
  '/tools/audio-tools/audio-to-text': 'text-indigo-500',
  '/tools/audio-tools/audio-trimmer': 'text-orange-500',
  '/tools/audio-tools/audio-waveform': 'text-cyan-500',
  '/tools/audio-tools/voice-recorder': 'text-blue-500',
  '/tools/converter-tools/color-converter': 'text-amber-500',
  '/tools/converter-tools/currency-converter': 'text-red-500',
  '/tools/converter-tools/mobi-to-epub': 'text-lime-500',
  '/tools/converter-tools/unit-converter': 'text-orange-500',
  '/tools/developer-tools/api-tester': 'text-rose-600',
  '/tools/developer-tools/aspect-ratio': 'text-emerald-400',
  '/tools/developer-tools/base64-encoder': 'text-fuchsia-500',
  '/tools/developer-tools/code-formatter': 'text-emerald-700',
  '/tools/developer-tools/code-minifier': 'text-lime-700',
  '/tools/developer-tools/color-picker': 'text-lime-400',
  '/tools/developer-tools/cron-expression': 'text-teal-700',
  '/tools/developer-tools/cron-expression-builder': 'text-cyan-700',
  '/tools/developer-tools/css-formatter': 'text-yellow-600',
  '/tools/developer-tools/csv-to-excel': 'text-teal-500',
  '/tools/developer-tools/csv-to-json': 'text-orange-600',
  '/tools/developer-tools/csv-to-sql': 'text-orange-700',
  '/tools/developer-tools/csv-to-tsv': 'text-lime-500',
  '/tools/developer-tools/diff-viewer': 'text-green-700',
  '/tools/developer-tools/env-to-json': 'text-yellow-700',
  '/tools/developer-tools/excel-to-csv': 'text-emerald-500',
  '/tools/developer-tools/excel-to-json': 'text-green-500',
  '/tools/developer-tools/hash-generator': 'text-rose-500',
  '/tools/developer-tools/hex-to-text': 'text-indigo-400',
  '/tools/developer-tools/html-encoder': 'text-cyan-400',
  '/tools/developer-tools/html-entity-decoder': 'text-sky-400',
  '/tools/developer-tools/html-formatter': 'text-lime-600',
  '/tools/developer-tools/javascript-formatter': 'text-emerald-600',
  '/tools/developer-tools/js-minifier': 'text-green-600',
  '/tools/developer-tools/json-formatter': 'text-indigo-500',
  '/tools/developer-tools/json-minifier': 'text-violet-500',
  '/tools/developer-tools/json-to-csharp': 'text-red-700',
  '/tools/developer-tools/json-to-csv': 'text-amber-600',
  '/tools/developer-tools/json-to-go': 'text-purple-400',
  '/tools/developer-tools/json-to-php': 'text-rose-400',
  '/tools/developer-tools/json-to-python': 'text-pink-400',
  '/tools/developer-tools/json-to-rust': 'text-fuchsia-400',
  '/tools/developer-tools/json-to-toml': 'text-blue-500',
  '/tools/developer-tools/json-to-typescript': 'text-violet-400',
  '/tools/developer-tools/json-to-xml': 'text-orange-500',
  '/tools/developer-tools/json-to-yaml': 'text-amber-400',
  '/tools/developer-tools/jwt-decoder': 'text-fuchsia-600',
  '/tools/developer-tools/markdown-editor': 'text-pink-600',
  '/tools/developer-tools/markdown-previewer': 'text-violet-600',
  '/tools/developer-tools/markdown-to-html': 'text-purple-600',
  '/tools/developer-tools/number-base-converter': 'text-red-400',
  '/tools/developer-tools/password-generator': 'text-red-600',
  '/tools/developer-tools/regex-tester': 'text-indigo-600',
  '/tools/developer-tools/scss-to-css': 'text-teal-600',
  '/tools/developer-tools/sql-formatter': 'text-blue-600',
  '/tools/developer-tools/sql-to-csv': 'text-amber-700',
  '/tools/developer-tools/timestamp-converter': 'text-green-400',
  '/tools/developer-tools/toml-to-json': 'text-cyan-500',
  '/tools/developer-tools/tsv-to-csv': 'text-amber-500',
  '/tools/developer-tools/typescript-to-js': 'text-cyan-600',
  '/tools/developer-tools/unicode-converter': 'text-blue-400',
  '/tools/developer-tools/url-encoder': 'text-pink-500',
  '/tools/developer-tools/url-parser': 'text-teal-400',
  '/tools/developer-tools/uuid-generator': 'text-purple-500',
  '/tools/developer-tools/xml-formatter': 'text-sky-600',
  '/tools/developer-tools/xml-to-json': 'text-red-500',
  '/tools/developer-tools/yaml-to-json': 'text-orange-400',
  '/tools/file-tools/base64-encoder': 'text-teal-500',
  '/tools/file-tools/file-comparator': 'text-cyan-500',
  '/tools/file-tools/file-converter': 'text-lime-500',
  '/tools/file-tools/file-encryptor': 'text-green-500',
  '/tools/file-tools/file-metadata': 'text-emerald-500',
  '/tools/file-tools/file-splitter': 'text-sky-500',
  '/tools/file-tools/tar-extractor': 'text-amber-500',
  '/tools/file-tools/zip-creator': 'text-orange-500',
  '/tools/file-tools/zip-extractor': 'text-red-500',
  '/tools/gif-tools/apng-to-gif': 'text-lime-500',
  '/tools/gif-tools/avi-to-gif': 'text-sky-500',
  '/tools/gif-tools/gif-compressor': 'text-indigo-500',
  '/tools/gif-tools/gif-maker': 'text-blue-500',
  '/tools/gif-tools/gif-to-apng': 'text-emerald-500',
  '/tools/gif-tools/gif-to-mp4': 'text-green-500',
  '/tools/gif-tools/image-to-gif': 'text-teal-500',
  '/tools/gif-tools/mov-to-gif': 'text-cyan-500',
  '/tools/gif-tools/mp4-to-gif': 'text-orange-500',
  '/tools/gif-tools/video-to-gif': 'text-red-500',
  '/tools/gif-tools/webm-to-gif': 'text-amber-500',
  '/tools/image-tools/add-border-to-image': 'text-blue-500',
  '/tools/image-tools/add-noise': 'text-yellow-600',
  '/tools/image-tools/add-text-to-image': 'text-cyan-500',
  '/tools/image-tools/add-vignette': 'text-lime-600',
  '/tools/image-tools/bmp-to-png': 'text-rose-600',
  '/tools/image-tools/brightness-contrast': 'text-indigo-500',
  '/tools/image-tools/duplicate-image-finder': 'text-purple-500',
  '/tools/image-tools/gif-to-png': 'text-pink-600',
  '/tools/image-tools/grayscale-converter': 'text-fuchsia-500',
  '/tools/image-tools/heic-to-jpg': 'text-green-600',
  '/tools/image-tools/heic-to-png': 'text-emerald-600',
  '/tools/image-tools/ico-to-png': 'text-amber-400',
  '/tools/image-tools/image-blur': 'text-pink-500',
  '/tools/image-tools/image-comparison': 'text-violet-500',
  '/tools/image-tools/image-compressor': 'text-red-500',
  '/tools/image-tools/image-converter': 'text-orange-500',
  '/tools/image-tools/image-cropper': 'text-lime-500',
  '/tools/image-tools/image-editor': 'text-sky-500',
  '/tools/image-tools/image-flip': 'text-emerald-500',
  '/tools/image-tools/image-inverter': 'text-rose-500',
  '/tools/image-tools/image-metadata': 'text-orange-600',
  '/tools/image-tools/image-pixelator': 'text-amber-600',
  '/tools/image-tools/image-resizer': 'text-amber-500',
  '/tools/image-tools/image-rotate': 'text-green-500',
  '/tools/image-tools/image-to-base64': 'text-lime-400',
  '/tools/image-tools/jpg-to-png': 'text-blue-600',
  '/tools/image-tools/jpg-to-webp': 'text-purple-600',
  '/tools/image-tools/png-to-ico': 'text-violet-600',
  '/tools/image-tools/png-to-jpg': 'text-sky-600',
  '/tools/image-tools/png-to-webp': 'text-fuchsia-600',
  '/tools/image-tools/round-corners': 'text-teal-500',
  '/tools/image-tools/sepia-filter': 'text-red-600',
  '/tools/image-tools/svg-to-png': 'text-indigo-600',
  '/tools/image-tools/tiff-to-jpg': 'text-orange-400',
  '/tools/image-tools/tiff-to-png': 'text-red-400',
  '/tools/image-tools/webp-to-jpg': 'text-cyan-600',
  '/tools/image-tools/webp-to-png': 'text-teal-600',
  '/tools/math-tools/fraction-calculator': 'text-green-500',
  '/tools/math-tools/number-base-converter': 'text-red-500',
  '/tools/math-tools/percentage-calculator': 'text-orange-500',
  '/tools/math-tools/roman-numeral-converter': 'text-amber-500',
  '/tools/math-tools/scientific-calculator': 'text-lime-500',
  '/tools/math-tools/statistics-calculator': 'text-emerald-500',
  '/tools/pdf-tools/epub-to-pdf': 'text-lime-600',
  '/tools/pdf-tools/excel-to-pdf': 'text-fuchsia-500',
  '/tools/pdf-tools/html-to-pdf': 'text-orange-600',
  '/tools/pdf-tools/image-to-pdf': 'text-cyan-500',
  '/tools/pdf-tools/jpg-to-pdf': 'text-indigo-500',
  '/tools/pdf-tools/markdown-to-pdf': 'text-yellow-600',
  '/tools/pdf-tools/mobi-to-pdf': 'text-green-600',
  '/tools/pdf-tools/pdf-ai-summary': 'text-green-400',
  '/tools/pdf-tools/pdf-compare': 'text-orange-400',
  '/tools/pdf-tools/pdf-compress': 'text-amber-500',
  '/tools/pdf-tools/pdf-crop': 'text-red-400',
  '/tools/pdf-tools/pdf-delete-pages': 'text-teal-600',
  '/tools/pdf-tools/pdf-editor': 'text-violet-600',
  '/tools/pdf-tools/pdf-extract-text': 'text-blue-600',
  '/tools/pdf-tools/pdf-forms': 'text-pink-600',
  '/tools/pdf-tools/pdf-merge': 'text-red-500',
  '/tools/pdf-tools/pdf-number-pages': 'text-indigo-600',
  '/tools/pdf-tools/pdf-ocr': 'text-fuchsia-600',
  '/tools/pdf-tools/pdf-organize': 'text-sky-600',
  '/tools/pdf-tools/pdf-protect': 'text-lime-500',
  '/tools/pdf-tools/pdf-redact': 'text-rose-600',
  '/tools/pdf-tools/pdf-reorder-pages': 'text-cyan-600',
  '/tools/pdf-tools/pdf-repair': 'text-lime-400',
  '/tools/pdf-tools/pdf-rotate': 'text-emerald-500',
  '/tools/pdf-tools/pdf-sign': 'text-purple-600',
  '/tools/pdf-tools/pdf-split': 'text-orange-500',
  '/tools/pdf-tools/pdf-to-excel': 'text-pink-500',
  '/tools/pdf-tools/pdf-to-html': 'text-emerald-600',
  '/tools/pdf-tools/pdf-to-image': 'text-sky-500',
  '/tools/pdf-tools/pdf-to-jpg': 'text-blue-500',
  '/tools/pdf-tools/pdf-to-pdfa': 'text-amber-400',
  '/tools/pdf-tools/pdf-to-ppt': 'text-rose-500',
  '/tools/pdf-tools/pdf-to-word': 'text-purple-500',
  '/tools/pdf-tools/pdf-translate': 'text-emerald-400',
  '/tools/pdf-tools/pdf-unlock': 'text-green-500',
  '/tools/pdf-tools/pdf-watermark': 'text-teal-500',
  '/tools/pdf-tools/ppt-to-pdf': 'text-red-600',
  '/tools/pdf-tools/text-to-pdf': 'text-amber-600',
  '/tools/pdf-tools/word-to-pdf': 'text-violet-500',
  '/tools/qr-barcodes-tools/barcode-generator': 'text-amber-500',
  '/tools/qr-barcodes-tools/qr-generator': 'text-red-500',
  '/tools/qr-barcodes-tools/qr-scanner': 'text-orange-500',
  '/tools/text-tools/ascii-art': 'text-rose-500',
  '/tools/text-tools/case-converter': 'text-orange-500',
  '/tools/text-tools/character-counter': 'text-fuchsia-500',
  '/tools/text-tools/duplicate-remover': 'text-lime-500',
  '/tools/text-tools/find-replace': 'text-emerald-500',
  '/tools/text-tools/lorem-ipsum': 'text-sky-500',
  '/tools/text-tools/sticky-notes': 'text-red-600',
  '/tools/text-tools/text-comparator': 'text-teal-500',
  '/tools/text-tools/text-encryptor': 'text-pink-500',
  '/tools/text-tools/text-repeater': 'text-purple-500',
  '/tools/text-tools/text-reverser': 'text-amber-500',
  '/tools/text-tools/text-sorter': 'text-green-500',
  '/tools/text-tools/text-to-list': 'text-indigo-500',
  '/tools/text-tools/text-truncator': 'text-violet-500',
  '/tools/text-tools/url-encoder': 'text-blue-500',
  '/tools/text-tools/whitespace-remover': 'text-cyan-500',
  '/tools/text-tools/word-counter': 'text-red-500',
  '/tools/video-tools/media-player': 'text-teal-500',
  '/tools/video-tools/screen-recorder': 'text-indigo-500',
  '/tools/video-tools/subtitle-generator': 'text-blue-500',
  '/tools/video-tools/video-compressor': 'text-orange-500',
  '/tools/video-tools/video-converter': 'text-amber-500',
  '/tools/video-tools/video-filter': 'text-pink-500',
  '/tools/video-tools/video-merger': 'text-violet-500',
  '/tools/video-tools/video-metadata': 'text-cyan-500',
  '/tools/video-tools/video-resizer': 'text-fuchsia-500',
  '/tools/video-tools/video-rotator': 'text-purple-500',
  '/tools/video-tools/video-screenshot': 'text-emerald-500',
  '/tools/video-tools/video-to-audio': 'text-red-500',
  '/tools/video-tools/video-to-gif': 'text-green-500',
  '/tools/video-tools/video-trimmer': 'text-lime-500',
  '/tools/video-tools/video-watermark': 'text-sky-500',
};

export const toolBgColors = {
  '/tools/ai-tools/ai-chatbot': 'bg-teal-500',
  '/tools/ai-tools/ai-detector': 'bg-sky-500',
  '/tools/ai-tools/ai-paraphraser': 'bg-fuchsia-500',
  '/tools/ai-tools/ai-translator': 'bg-green-500',
  '/tools/ai-tools/ai-writer': 'bg-cyan-500',
  '/tools/ai-tools/audio-transcriber': 'bg-blue-500',
  '/tools/ai-tools/background-remover': 'bg-red-500',
  '/tools/ai-tools/data-extractor': 'bg-purple-500',
  '/tools/ai-tools/email-generator': 'bg-pink-500',
  '/tools/ai-tools/grammar-fixer': 'bg-amber-500',
  '/tools/ai-tools/image-captioner': 'bg-violet-500',
  '/tools/ai-tools/image-generator': 'bg-emerald-500',
  '/tools/ai-tools/image-upscaler': 'bg-orange-500',
  '/tools/ai-tools/keyword-extractor': 'bg-rose-500',
  '/tools/ai-tools/sentiment-analyzer': 'bg-indigo-500',
  '/tools/ai-tools/text-summarizer': 'bg-lime-500',
  '/tools/audio-tools/audio-booster': 'bg-emerald-500',
  '/tools/audio-tools/audio-compressor': 'bg-amber-500',
  '/tools/audio-tools/audio-converter': 'bg-red-500',
  '/tools/audio-tools/audio-equalizer': 'bg-teal-500',
  '/tools/audio-tools/audio-merger': 'bg-lime-500',
  '/tools/audio-tools/audio-metadata': 'bg-sky-500',
  '/tools/audio-tools/audio-splitter': 'bg-green-500',
  '/tools/audio-tools/audio-to-text': 'bg-indigo-500',
  '/tools/audio-tools/audio-trimmer': 'bg-orange-500',
  '/tools/audio-tools/audio-waveform': 'bg-cyan-500',
  '/tools/audio-tools/voice-recorder': 'bg-blue-500',
  '/tools/converter-tools/color-converter': 'bg-amber-500',
  '/tools/converter-tools/currency-converter': 'bg-red-500',
  '/tools/converter-tools/mobi-to-epub': 'bg-lime-500',
  '/tools/converter-tools/unit-converter': 'bg-orange-500',
  '/tools/developer-tools/api-tester': 'bg-rose-600',
  '/tools/developer-tools/aspect-ratio': 'bg-emerald-400',
  '/tools/developer-tools/base64-encoder': 'bg-fuchsia-500',
  '/tools/developer-tools/code-formatter': 'bg-emerald-700',
  '/tools/developer-tools/code-minifier': 'bg-lime-700',
  '/tools/developer-tools/color-picker': 'bg-lime-400',
  '/tools/developer-tools/cron-expression': 'bg-teal-700',
  '/tools/developer-tools/cron-expression-builder': 'bg-cyan-700',
  '/tools/developer-tools/css-formatter': 'bg-yellow-600',
  '/tools/developer-tools/csv-to-excel': 'bg-teal-500',
  '/tools/developer-tools/csv-to-json': 'bg-orange-600',
  '/tools/developer-tools/csv-to-sql': 'bg-orange-700',
  '/tools/developer-tools/csv-to-tsv': 'bg-lime-500',
  '/tools/developer-tools/diff-viewer': 'bg-green-700',
  '/tools/developer-tools/env-to-json': 'bg-yellow-700',
  '/tools/developer-tools/excel-to-csv': 'bg-emerald-500',
  '/tools/developer-tools/excel-to-json': 'bg-green-500',
  '/tools/developer-tools/hash-generator': 'bg-rose-500',
  '/tools/developer-tools/hex-to-text': 'bg-indigo-400',
  '/tools/developer-tools/html-encoder': 'bg-cyan-400',
  '/tools/developer-tools/html-entity-decoder': 'bg-sky-400',
  '/tools/developer-tools/html-formatter': 'bg-lime-600',
  '/tools/developer-tools/javascript-formatter': 'bg-emerald-600',
  '/tools/developer-tools/js-minifier': 'bg-green-600',
  '/tools/developer-tools/json-formatter': 'bg-indigo-500',
  '/tools/developer-tools/json-minifier': 'bg-violet-500',
  '/tools/developer-tools/json-to-csharp': 'bg-red-700',
  '/tools/developer-tools/json-to-csv': 'bg-amber-600',
  '/tools/developer-tools/json-to-go': 'bg-purple-400',
  '/tools/developer-tools/json-to-php': 'bg-rose-400',
  '/tools/developer-tools/json-to-python': 'bg-pink-400',
  '/tools/developer-tools/json-to-rust': 'bg-fuchsia-400',
  '/tools/developer-tools/json-to-toml': 'bg-blue-500',
  '/tools/developer-tools/json-to-typescript': 'bg-violet-400',
  '/tools/developer-tools/json-to-xml': 'bg-orange-500',
  '/tools/developer-tools/json-to-yaml': 'bg-amber-400',
  '/tools/developer-tools/jwt-decoder': 'bg-fuchsia-600',
  '/tools/developer-tools/markdown-editor': 'bg-pink-600',
  '/tools/developer-tools/markdown-previewer': 'bg-violet-600',
  '/tools/developer-tools/markdown-to-html': 'bg-purple-600',
  '/tools/developer-tools/number-base-converter': 'bg-red-400',
  '/tools/developer-tools/password-generator': 'bg-red-600',
  '/tools/developer-tools/regex-tester': 'bg-indigo-600',
  '/tools/developer-tools/scss-to-css': 'bg-teal-600',
  '/tools/developer-tools/sql-formatter': 'bg-blue-600',
  '/tools/developer-tools/sql-to-csv': 'bg-amber-700',
  '/tools/developer-tools/timestamp-converter': 'bg-green-400',
  '/tools/developer-tools/toml-to-json': 'bg-cyan-500',
  '/tools/developer-tools/tsv-to-csv': 'bg-amber-500',
  '/tools/developer-tools/typescript-to-js': 'bg-cyan-600',
  '/tools/developer-tools/unicode-converter': 'bg-blue-400',
  '/tools/developer-tools/url-encoder': 'bg-pink-500',
  '/tools/developer-tools/url-parser': 'bg-teal-400',
  '/tools/developer-tools/uuid-generator': 'bg-purple-500',
  '/tools/developer-tools/xml-formatter': 'bg-sky-600',
  '/tools/developer-tools/xml-to-json': 'bg-red-500',
  '/tools/developer-tools/yaml-to-json': 'bg-orange-400',
  '/tools/file-tools/base64-encoder': 'bg-teal-500',
  '/tools/file-tools/file-comparator': 'bg-cyan-500',
  '/tools/file-tools/file-converter': 'bg-lime-500',
  '/tools/file-tools/file-encryptor': 'bg-green-500',
  '/tools/file-tools/file-metadata': 'bg-emerald-500',
  '/tools/file-tools/file-splitter': 'bg-sky-500',
  '/tools/file-tools/tar-extractor': 'bg-amber-500',
  '/tools/file-tools/zip-creator': 'bg-orange-500',
  '/tools/file-tools/zip-extractor': 'bg-red-500',
  '/tools/gif-tools/apng-to-gif': 'bg-lime-500',
  '/tools/gif-tools/avi-to-gif': 'bg-sky-500',
  '/tools/gif-tools/gif-compressor': 'bg-indigo-500',
  '/tools/gif-tools/gif-maker': 'bg-blue-500',
  '/tools/gif-tools/gif-to-apng': 'bg-emerald-500',
  '/tools/gif-tools/gif-to-mp4': 'bg-green-500',
  '/tools/gif-tools/image-to-gif': 'bg-teal-500',
  '/tools/gif-tools/mov-to-gif': 'bg-cyan-500',
  '/tools/gif-tools/mp4-to-gif': 'bg-orange-500',
  '/tools/gif-tools/video-to-gif': 'bg-red-500',
  '/tools/gif-tools/webm-to-gif': 'bg-amber-500',
  '/tools/image-tools/add-border-to-image': 'bg-blue-500',
  '/tools/image-tools/add-noise': 'bg-yellow-600',
  '/tools/image-tools/add-text-to-image': 'bg-cyan-500',
  '/tools/image-tools/add-vignette': 'bg-lime-600',
  '/tools/image-tools/bmp-to-png': 'bg-rose-600',
  '/tools/image-tools/brightness-contrast': 'bg-indigo-500',
  '/tools/image-tools/duplicate-image-finder': 'bg-purple-500',
  '/tools/image-tools/gif-to-png': 'bg-pink-600',
  '/tools/image-tools/grayscale-converter': 'bg-fuchsia-500',
  '/tools/image-tools/heic-to-jpg': 'bg-green-600',
  '/tools/image-tools/heic-to-png': 'bg-emerald-600',
  '/tools/image-tools/ico-to-png': 'bg-amber-400',
  '/tools/image-tools/image-blur': 'bg-pink-500',
  '/tools/image-tools/image-comparison': 'bg-violet-500',
  '/tools/image-tools/image-compressor': 'bg-red-500',
  '/tools/image-tools/image-converter': 'bg-orange-500',
  '/tools/image-tools/image-cropper': 'bg-lime-500',
  '/tools/image-tools/image-editor': 'bg-sky-500',
  '/tools/image-tools/image-flip': 'bg-emerald-500',
  '/tools/image-tools/image-inverter': 'bg-rose-500',
  '/tools/image-tools/image-metadata': 'bg-orange-600',
  '/tools/image-tools/image-pixelator': 'bg-amber-600',
  '/tools/image-tools/image-resizer': 'bg-amber-500',
  '/tools/image-tools/image-rotate': 'bg-green-500',
  '/tools/image-tools/image-to-base64': 'bg-lime-400',
  '/tools/image-tools/jpg-to-png': 'bg-blue-600',
  '/tools/image-tools/jpg-to-webp': 'bg-purple-600',
  '/tools/image-tools/png-to-ico': 'bg-violet-600',
  '/tools/image-tools/png-to-jpg': 'bg-sky-600',
  '/tools/image-tools/png-to-webp': 'bg-fuchsia-600',
  '/tools/image-tools/round-corners': 'bg-teal-500',
  '/tools/image-tools/sepia-filter': 'bg-red-600',
  '/tools/image-tools/svg-to-png': 'bg-indigo-600',
  '/tools/image-tools/tiff-to-jpg': 'bg-orange-400',
  '/tools/image-tools/tiff-to-png': 'bg-red-400',
  '/tools/image-tools/webp-to-jpg': 'bg-cyan-600',
  '/tools/image-tools/webp-to-png': 'bg-teal-600',
  '/tools/math-tools/fraction-calculator': 'bg-green-500',
  '/tools/math-tools/number-base-converter': 'bg-red-500',
  '/tools/math-tools/percentage-calculator': 'bg-orange-500',
  '/tools/math-tools/roman-numeral-converter': 'bg-amber-500',
  '/tools/math-tools/scientific-calculator': 'bg-lime-500',
  '/tools/math-tools/statistics-calculator': 'bg-emerald-500',
  '/tools/pdf-tools/epub-to-pdf': 'bg-lime-600',
  '/tools/pdf-tools/excel-to-pdf': 'bg-fuchsia-500',
  '/tools/pdf-tools/html-to-pdf': 'bg-orange-600',
  '/tools/pdf-tools/image-to-pdf': 'bg-cyan-500',
  '/tools/pdf-tools/jpg-to-pdf': 'bg-indigo-500',
  '/tools/pdf-tools/markdown-to-pdf': 'bg-yellow-600',
  '/tools/pdf-tools/mobi-to-pdf': 'bg-green-600',
  '/tools/pdf-tools/pdf-ai-summary': 'bg-green-400',
  '/tools/pdf-tools/pdf-compare': 'bg-orange-400',
  '/tools/pdf-tools/pdf-compress': 'bg-amber-500',
  '/tools/pdf-tools/pdf-crop': 'bg-red-400',
  '/tools/pdf-tools/pdf-delete-pages': 'bg-teal-600',
  '/tools/pdf-tools/pdf-editor': 'bg-violet-600',
  '/tools/pdf-tools/pdf-extract-text': 'bg-blue-600',
  '/tools/pdf-tools/pdf-forms': 'bg-pink-600',
  '/tools/pdf-tools/pdf-merge': 'bg-red-500',
  '/tools/pdf-tools/pdf-number-pages': 'bg-indigo-600',
  '/tools/pdf-tools/pdf-ocr': 'bg-fuchsia-600',
  '/tools/pdf-tools/pdf-organize': 'bg-sky-600',
  '/tools/pdf-tools/pdf-protect': 'bg-lime-500',
  '/tools/pdf-tools/pdf-redact': 'bg-rose-600',
  '/tools/pdf-tools/pdf-reorder-pages': 'bg-cyan-600',
  '/tools/pdf-tools/pdf-repair': 'bg-lime-400',
  '/tools/pdf-tools/pdf-rotate': 'bg-emerald-500',
  '/tools/pdf-tools/pdf-sign': 'bg-purple-600',
  '/tools/pdf-tools/pdf-split': 'bg-orange-500',
  '/tools/pdf-tools/pdf-to-excel': 'bg-pink-500',
  '/tools/pdf-tools/pdf-to-html': 'bg-emerald-600',
  '/tools/pdf-tools/pdf-to-image': 'bg-sky-500',
  '/tools/pdf-tools/pdf-to-jpg': 'bg-blue-500',
  '/tools/pdf-tools/pdf-to-pdfa': 'bg-amber-400',
  '/tools/pdf-tools/pdf-to-ppt': 'bg-rose-500',
  '/tools/pdf-tools/pdf-to-word': 'bg-purple-500',
  '/tools/pdf-tools/pdf-translate': 'bg-emerald-400',
  '/tools/pdf-tools/pdf-unlock': 'bg-green-500',
  '/tools/pdf-tools/pdf-watermark': 'bg-teal-500',
  '/tools/pdf-tools/ppt-to-pdf': 'bg-red-600',
  '/tools/pdf-tools/text-to-pdf': 'bg-amber-600',
  '/tools/pdf-tools/word-to-pdf': 'bg-violet-500',
  '/tools/qr-barcodes-tools/barcode-generator': 'bg-amber-500',
  '/tools/qr-barcodes-tools/qr-generator': 'bg-red-500',
  '/tools/qr-barcodes-tools/qr-scanner': 'bg-orange-500',
  '/tools/text-tools/ascii-art': 'bg-rose-500',
  '/tools/text-tools/case-converter': 'bg-orange-500',
  '/tools/text-tools/character-counter': 'bg-fuchsia-500',
  '/tools/text-tools/duplicate-remover': 'bg-lime-500',
  '/tools/text-tools/find-replace': 'bg-emerald-500',
  '/tools/text-tools/lorem-ipsum': 'bg-sky-500',
  '/tools/text-tools/sticky-notes': 'bg-red-600',
  '/tools/text-tools/text-comparator': 'bg-teal-500',
  '/tools/text-tools/text-encryptor': 'bg-pink-500',
  '/tools/text-tools/text-repeater': 'bg-purple-500',
  '/tools/text-tools/text-reverser': 'bg-amber-500',
  '/tools/text-tools/text-sorter': 'bg-green-500',
  '/tools/text-tools/text-to-list': 'bg-indigo-500',
  '/tools/text-tools/text-truncator': 'bg-violet-500',
  '/tools/text-tools/url-encoder': 'bg-blue-500',
  '/tools/text-tools/whitespace-remover': 'bg-cyan-500',
  '/tools/text-tools/word-counter': 'bg-red-500',
  '/tools/video-tools/media-player': 'bg-teal-500',
  '/tools/video-tools/screen-recorder': 'bg-indigo-500',
  '/tools/video-tools/subtitle-generator': 'bg-blue-500',
  '/tools/video-tools/video-compressor': 'bg-orange-500',
  '/tools/video-tools/video-converter': 'bg-amber-500',
  '/tools/video-tools/video-filter': 'bg-pink-500',
  '/tools/video-tools/video-merger': 'bg-violet-500',
  '/tools/video-tools/video-metadata': 'bg-cyan-500',
  '/tools/video-tools/video-resizer': 'bg-fuchsia-500',
  '/tools/video-tools/video-rotator': 'bg-purple-500',
  '/tools/video-tools/video-screenshot': 'bg-emerald-500',
  '/tools/video-tools/video-to-audio': 'bg-red-500',
  '/tools/video-tools/video-to-gif': 'bg-green-500',
  '/tools/video-tools/video-trimmer': 'bg-lime-500',
  '/tools/video-tools/video-watermark': 'bg-sky-500',
};

// Text color for a tool's title icon (ToolLayout), matching its card color on
// the category grid and its mega-menu badge.
export function getToolTitleColor(pathname) {
  return toolTextColors[pathname];
}

export function ToolIcon({ slug, className }) {
  return createElement(getToolIcon(slug), { className, 'aria-hidden': true });
}

export function CategoryIcon({ slug, className }) {
  return createElement(getCategoryIcon(slug), { className, 'aria-hidden': true });
}

// Decorative, non-tool icons reused on the homepage (badges/stats).
export const homeIcons = {
  noSignup: Zap,
  secure: ShieldCheck,
  allDevices: Smartphone,
  noInstall: Cloud,
  totalTools: Wrench,
  categories: LayoutGrid,
  languages: Languages,
  countries: Globe,
};
