'use client';
import { useState } from 'react';
import SeoContent from '../../../components/SeoContent';
import { checkPromptLength } from '@/lib/quota/limits';

export default function AIWriterPage() {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const process = async () => {
    if (!input.trim()) return;
    setLoading(true);
    setOutput('');
    setError('');
    try {
      const lengthCheck = checkPromptLength(input);
      if (!lengthCheck.ok) { setError(lengthCheck.message); setLoading(false); return; }
      const response = await fetch('/api/ai', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          system: 'You are a professional content writer. Generate high-quality, engaging content based on the user input. Be creative and detailed.',
          prompt: input,
          tool: 'ai-writer',
        }),
      });
      const data = await response.json();
      if (data.text) setOutput(data.text);
      else setError(data.error || 'No response received');
    } catch(e) { setError('Error: ' + e.message); }
    setLoading(false);
  };

  return (
    <div className="min-h-screen bg-neutral-100 p-6">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold text-center mb-2">AI Writer</h1>
        <p className="text-neutral-500 text-center mb-8">Generate text content with AI</p>
        <div className="bg-white border border-neutral-200 rounded-xl shadow-sm p-6 space-y-4">
          <textarea className="w-full bg-neutral-50 border border-neutral-200 rounded-xl p-4 text-sm h-48 resize-none" placeholder="Describe what you want to write..." value={input} onChange={e => setInput(e.target.value)} />
          <button onClick={process} disabled={!input.trim() || loading} className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:bg-neutral-200 disabled:text-gray-600 rounded-xl py-3 font-semibold transition">
            {loading ? 'Processing...' : 'Generate Content'}
          </button>
          {error && <p className="text-red-400 text-center text-sm">{error}</p>}
          {output && (
            <div className="space-y-2">
              <label className="block text-sm text-neutral-500">Result</label>
              <textarea className="w-full bg-neutral-50 border border-neutral-200 rounded-xl p-4 text-sm h-48 resize-none" value={output} readOnly />
              <button onClick={() => navigator.clipboard.writeText(output)} className="w-full bg-green-600 hover:bg-green-500 rounded-xl py-2 font-semibold transition">Copy</button>
            </div>
          )}
        </div>
      </div>
      <SeoContent
        title="AI Writer"
        description="AI Writer is a free online tool that uses OpenAI's GPT-4o mini model to generate written content from a simple description. Describe what you want written — a blog intro, marketing copy, a creative piece — and the AI produces a draft you can copy and refine."
        howTo={[
          "Describe what you want written in the input field, including topic, keywords, and any specific requirements.",
          "Click the 'Generate Content' button to send your description to the AI.",
          "Wait a moment while the AI generates a draft.",
          "Review the generated content, edit it as needed, and copy your finished piece."
        ]}
        faqs={[
          { q: "Is AI Writer really free to use?", a: "Yes, AI Writer is free to use with no signup or subscription required." },
          { q: "Can I use AI Writer content for commercial purposes?", a: "Yes, content generated by AI Writer can be used for commercial purposes such as blogs, websites, and marketing materials." },
          { q: "How long does it take to generate content?", a: "Most content is generated within a few seconds, depending on the length and complexity of your request." },
          { q: "Will the AI content be plagiarism-free?", a: "AI Writer generates a new draft based on your description, but as with any AI-generated text, you should review and verify it before publishing." }
        ]}
        tips={[
          "Provide a detailed, specific description to get content that matches your exact needs and style.",
          "Mention relevant keywords in your description to help the generated content stay on-topic.",
          "Always proofread and personalize AI-generated content to add your own voice and ensure accuracy.",
          "Regenerate with a refined description if the first draft isn't quite what you're looking for."
        ]}
      />
    </div>
  );
}