// Every URL this site has ever served at a path that no longer exists,
// reconstructed from git history (see docs/specs/2026-09-01-legacy-url-redirects.md
// for the audit method). Each entry is a permanent (301) redirect from an old
// path to where that same tool/page lives today. Source of the three groups:
//
// 1. Flat tool URLs (/tools/<slug>) from app/sitemap.ts before commit
//    37d4528b (2026-08-06) rewrote it to walk the categorized filesystem
//    tree -- until then, the sitemap submitted a flat URL for every tool,
//    none of which were ever actually served (every tool page has always
//    lived at /tools/<category>/<slug>).
// 2. /tools/media-tools/<slug> URLs: media-tools was a real, live category
//    with real pages (confirmed via git history) before being split into
//    audio-tools, gif-tools, and video-tools.
// 3. Two one-off moves: the bare /tools/media-tools category (no single
//    successor -- see the spec for why video-tools was chosen) and
//    /login -> /signin.
export type LegacyRedirect = { source: string; destination: string; permanent: true };

export const legacyRedirects: LegacyRedirect[] = [
  // --- flat /tools/<slug> -> /tools/<category>/<slug> (pre-2026-08-06 sitemap) ---
  { source: "/tools/pdf-merge", destination: "/tools/pdf-tools/pdf-merge", permanent: true },
  { source: "/tools/pdf-split", destination: "/tools/pdf-tools/pdf-split", permanent: true },
  { source: "/tools/pdf-compress", destination: "/tools/pdf-tools/pdf-compress", permanent: true },
  { source: "/tools/pdf-to-image", destination: "/tools/pdf-tools/pdf-to-image", permanent: true },
  { source: "/tools/pdf-to-word", destination: "/tools/pdf-tools/pdf-to-word", permanent: true },
  { source: "/tools/pdf-to-html", destination: "/tools/pdf-tools/pdf-to-html", permanent: true },
  { source: "/tools/pdf-protect", destination: "/tools/pdf-tools/pdf-protect", permanent: true },
  { source: "/tools/pdf-watermark", destination: "/tools/pdf-tools/pdf-watermark", permanent: true },
  { source: "/tools/pdf-rotate", destination: "/tools/pdf-tools/pdf-rotate", permanent: true },
  { source: "/tools/pdf-extract-text", destination: "/tools/pdf-tools/pdf-extract-text", permanent: true },
  { source: "/tools/pdf-delete-pages", destination: "/tools/pdf-tools/pdf-delete-pages", permanent: true },
  { source: "/tools/pdf-reorder-pages", destination: "/tools/pdf-tools/pdf-reorder-pages", permanent: true },
  { source: "/tools/pdf-number-pages", destination: "/tools/pdf-tools/pdf-number-pages", permanent: true },
  { source: "/tools/image-to-pdf", destination: "/tools/pdf-tools/image-to-pdf", permanent: true },
  { source: "/tools/word-to-pdf", destination: "/tools/pdf-tools/word-to-pdf", permanent: true },
  { source: "/tools/excel-to-pdf", destination: "/tools/pdf-tools/excel-to-pdf", permanent: true },
  { source: "/tools/epub-to-pdf", destination: "/tools/pdf-tools/epub-to-pdf", permanent: true },
  { source: "/tools/markdown-to-pdf", destination: "/tools/pdf-tools/markdown-to-pdf", permanent: true },
  { source: "/tools/html-to-pdf", destination: "/tools/pdf-tools/html-to-pdf", permanent: true },
  { source: "/tools/text-to-pdf", destination: "/tools/pdf-tools/text-to-pdf", permanent: true },
  { source: "/tools/image-compressor", destination: "/tools/image-tools/image-compressor", permanent: true },
  { source: "/tools/image-converter", destination: "/tools/image-tools/image-converter", permanent: true },
  { source: "/tools/image-resizer", destination: "/tools/image-tools/image-resizer", permanent: true },
  { source: "/tools/image-cropper", destination: "/tools/image-tools/image-cropper", permanent: true },
  { source: "/tools/image-to-base64", destination: "/tools/image-tools/image-to-base64", permanent: true },
  { source: "/tools/image-to-gif", destination: "/tools/gif-tools/image-to-gif", permanent: true },
  { source: "/tools/image-upscaler", destination: "/tools/ai-tools/image-upscaler", permanent: true },
  { source: "/tools/jpg-to-png", destination: "/tools/image-tools/jpg-to-png", permanent: true },
  { source: "/tools/jpg-to-webp", destination: "/tools/image-tools/jpg-to-webp", permanent: true },
  { source: "/tools/png-to-jpg", destination: "/tools/image-tools/png-to-jpg", permanent: true },
  { source: "/tools/png-to-webp", destination: "/tools/image-tools/png-to-webp", permanent: true },
  { source: "/tools/png-to-ico", destination: "/tools/image-tools/png-to-ico", permanent: true },
  { source: "/tools/webp-to-jpg", destination: "/tools/image-tools/webp-to-jpg", permanent: true },
  { source: "/tools/webp-to-png", destination: "/tools/image-tools/webp-to-png", permanent: true },
  { source: "/tools/bmp-to-png", destination: "/tools/image-tools/bmp-to-png", permanent: true },
  { source: "/tools/heic-to-jpg", destination: "/tools/image-tools/heic-to-jpg", permanent: true },
  { source: "/tools/heic-to-png", destination: "/tools/image-tools/heic-to-png", permanent: true },
  { source: "/tools/svg-to-png", destination: "/tools/image-tools/svg-to-png", permanent: true },
  { source: "/tools/ico-to-png", destination: "/tools/image-tools/ico-to-png", permanent: true },
  { source: "/tools/tiff-to-jpg", destination: "/tools/image-tools/tiff-to-jpg", permanent: true },
  { source: "/tools/tiff-to-png", destination: "/tools/image-tools/tiff-to-png", permanent: true },
  { source: "/tools/image-editor", destination: "/tools/image-tools/image-editor", permanent: true },
  { source: "/tools/image-rotate", destination: "/tools/image-tools/image-rotate", permanent: true },
  { source: "/tools/image-flip", destination: "/tools/image-tools/image-flip", permanent: true },
  { source: "/tools/grayscale-converter", destination: "/tools/image-tools/grayscale-converter", permanent: true },
  { source: "/tools/brightness-contrast", destination: "/tools/image-tools/brightness-contrast", permanent: true },
  { source: "/tools/image-blur", destination: "/tools/image-tools/image-blur", permanent: true },
  { source: "/tools/sepia-filter", destination: "/tools/image-tools/sepia-filter", permanent: true },
  { source: "/tools/image-inverter", destination: "/tools/image-tools/image-inverter", permanent: true },
  { source: "/tools/add-border-to-image", destination: "/tools/image-tools/add-border-to-image", permanent: true },
  { source: "/tools/round-corners", destination: "/tools/image-tools/round-corners", permanent: true },
  { source: "/tools/add-text-to-image", destination: "/tools/image-tools/add-text-to-image", permanent: true },
  { source: "/tools/add-vignette", destination: "/tools/image-tools/add-vignette", permanent: true },
  { source: "/tools/add-noise", destination: "/tools/image-tools/add-noise", permanent: true },
  { source: "/tools/image-pixelator", destination: "/tools/image-tools/image-pixelator", permanent: true },
  { source: "/tools/image-comparison", destination: "/tools/image-tools/image-comparison", permanent: true },
  { source: "/tools/duplicate-image-finder", destination: "/tools/image-tools/duplicate-image-finder", permanent: true },
  { source: "/tools/aspect-ratio", destination: "/tools/developer-tools/aspect-ratio", permanent: true },
  { source: "/tools/image-metadata", destination: "/tools/image-tools/image-metadata", permanent: true },
  { source: "/tools/image-generator", destination: "/tools/ai-tools/image-generator", permanent: true },
  { source: "/tools/video-converter", destination: "/tools/video-tools/video-converter", permanent: true },
  { source: "/tools/video-compressor", destination: "/tools/video-tools/video-compressor", permanent: true },
  { source: "/tools/video-to-audio", destination: "/tools/video-tools/video-to-audio", permanent: true },
  { source: "/tools/video-trimmer", destination: "/tools/video-tools/video-trimmer", permanent: true },
  { source: "/tools/video-merger", destination: "/tools/video-tools/video-merger", permanent: true },
  { source: "/tools/video-resizer", destination: "/tools/video-tools/video-resizer", permanent: true },
  { source: "/tools/video-rotator", destination: "/tools/video-tools/video-rotator", permanent: true },
  { source: "/tools/video-watermark", destination: "/tools/video-tools/video-watermark", permanent: true },
  { source: "/tools/video-filter", destination: "/tools/video-tools/video-filter", permanent: true },
  { source: "/tools/video-screenshot", destination: "/tools/video-tools/video-screenshot", permanent: true },
  { source: "/tools/video-metadata", destination: "/tools/video-tools/video-metadata", permanent: true },
  { source: "/tools/video-to-gif", destination: "/tools/video-tools/video-to-gif", permanent: true },
  { source: "/tools/subtitle-generator", destination: "/tools/video-tools/subtitle-generator", permanent: true },
  { source: "/tools/screen-recorder", destination: "/tools/video-tools/screen-recorder", permanent: true },
  { source: "/tools/media-player", destination: "/tools/video-tools/media-player", permanent: true },
  { source: "/tools/audio-converter", destination: "/tools/audio-tools/audio-converter", permanent: true },
  { source: "/tools/audio-compressor", destination: "/tools/audio-tools/audio-compressor", permanent: true },
  { source: "/tools/audio-trimmer", destination: "/tools/audio-tools/audio-trimmer", permanent: true },
  { source: "/tools/audio-merger", destination: "/tools/audio-tools/audio-merger", permanent: true },
  { source: "/tools/audio-splitter", destination: "/tools/audio-tools/audio-splitter", permanent: true },
  { source: "/tools/audio-booster", destination: "/tools/audio-tools/audio-booster", permanent: true },
  { source: "/tools/audio-equalizer", destination: "/tools/audio-tools/audio-equalizer", permanent: true },
  { source: "/tools/audio-to-text", destination: "/tools/audio-tools/audio-to-text", permanent: true },
  { source: "/tools/audio-waveform", destination: "/tools/audio-tools/audio-waveform", permanent: true },
  { source: "/tools/audio-metadata", destination: "/tools/audio-tools/audio-metadata", permanent: true },
  { source: "/tools/voice-recorder", destination: "/tools/audio-tools/voice-recorder", permanent: true },
  { source: "/tools/word-counter", destination: "/tools/text-tools/word-counter", permanent: true },
  { source: "/tools/character-counter", destination: "/tools/text-tools/character-counter", permanent: true },
  { source: "/tools/case-converter", destination: "/tools/text-tools/case-converter", permanent: true },
  { source: "/tools/text-reverser", destination: "/tools/text-tools/text-reverser", permanent: true },
  { source: "/tools/text-sorter", destination: "/tools/text-tools/text-sorter", permanent: true },
  { source: "/tools/text-comparator", destination: "/tools/text-tools/text-comparator", permanent: true },
  { source: "/tools/text-encryptor", destination: "/tools/text-tools/text-encryptor", permanent: true },
  { source: "/tools/text-repeater", destination: "/tools/text-tools/text-repeater", permanent: true },
  { source: "/tools/text-truncator", destination: "/tools/text-tools/text-truncator", permanent: true },
  { source: "/tools/whitespace-remover", destination: "/tools/text-tools/whitespace-remover", permanent: true },
  { source: "/tools/find-replace", destination: "/tools/text-tools/find-replace", permanent: true },
  { source: "/tools/duplicate-remover", destination: "/tools/text-tools/duplicate-remover", permanent: true },
  { source: "/tools/lorem-ipsum", destination: "/tools/text-tools/lorem-ipsum", permanent: true },
  { source: "/tools/text-to-list", destination: "/tools/text-tools/text-to-list", permanent: true },
  { source: "/tools/text-summarizer", destination: "/tools/ai-tools/text-summarizer", permanent: true },
  { source: "/tools/keyword-extractor", destination: "/tools/ai-tools/keyword-extractor", permanent: true },
  { source: "/tools/sentiment-analyzer", destination: "/tools/ai-tools/sentiment-analyzer", permanent: true },
  { source: "/tools/json-formatter", destination: "/tools/developer-tools/json-formatter", permanent: true },
  { source: "/tools/json-minifier", destination: "/tools/developer-tools/json-minifier", permanent: true },
  { source: "/tools/xml-formatter", destination: "/tools/developer-tools/xml-formatter", permanent: true },
  { source: "/tools/html-formatter", destination: "/tools/developer-tools/html-formatter", permanent: true },
  { source: "/tools/css-formatter", destination: "/tools/developer-tools/css-formatter", permanent: true },
  { source: "/tools/javascript-formatter", destination: "/tools/developer-tools/javascript-formatter", permanent: true },
  { source: "/tools/sql-formatter", destination: "/tools/developer-tools/sql-formatter", permanent: true },
  { source: "/tools/hash-generator", destination: "/tools/developer-tools/hash-generator", permanent: true },
  { source: "/tools/base64-encoder", destination: "/tools/file-tools/base64-encoder", permanent: true },
  { source: "/tools/url-encoder", destination: "/tools/text-tools/url-encoder", permanent: true },
  { source: "/tools/jwt-decoder", destination: "/tools/developer-tools/jwt-decoder", permanent: true },
  { source: "/tools/regex-tester", destination: "/tools/developer-tools/regex-tester", permanent: true },
  { source: "/tools/diff-viewer", destination: "/tools/developer-tools/diff-viewer", permanent: true },
  { source: "/tools/code-formatter", destination: "/tools/developer-tools/code-formatter", permanent: true },
  { source: "/tools/code-minifier", destination: "/tools/developer-tools/code-minifier", permanent: true },
  { source: "/tools/color-picker", destination: "/tools/developer-tools/color-picker", permanent: true },
  { source: "/tools/uuid-generator", destination: "/tools/developer-tools/uuid-generator", permanent: true },
  { source: "/tools/timestamp-converter", destination: "/tools/developer-tools/timestamp-converter", permanent: true },
  { source: "/tools/cron-expression-builder", destination: "/tools/developer-tools/cron-expression-builder", permanent: true },
  { source: "/tools/json-to-csv", destination: "/tools/developer-tools/json-to-csv", permanent: true },
  { source: "/tools/json-to-xml", destination: "/tools/developer-tools/json-to-xml", permanent: true },
  { source: "/tools/json-to-yaml", destination: "/tools/developer-tools/json-to-yaml", permanent: true },
  { source: "/tools/csv-to-json", destination: "/tools/developer-tools/csv-to-json", permanent: true },
  { source: "/tools/xml-to-json", destination: "/tools/developer-tools/xml-to-json", permanent: true },
  { source: "/tools/yaml-to-json", destination: "/tools/developer-tools/yaml-to-json", permanent: true },
  { source: "/tools/toml-to-json", destination: "/tools/developer-tools/toml-to-json", permanent: true },
  { source: "/tools/env-to-json", destination: "/tools/developer-tools/env-to-json", permanent: true },
  { source: "/tools/zip-extractor", destination: "/tools/file-tools/zip-extractor", permanent: true },
  { source: "/tools/zip-creator", destination: "/tools/file-tools/zip-creator", permanent: true },
  { source: "/tools/tar-extractor", destination: "/tools/file-tools/tar-extractor", permanent: true },
  { source: "/tools/file-converter", destination: "/tools/file-tools/file-converter", permanent: true },
  { source: "/tools/file-encryptor", destination: "/tools/file-tools/file-encryptor", permanent: true },
  { source: "/tools/file-comparator", destination: "/tools/file-tools/file-comparator", permanent: true },
  { source: "/tools/file-splitter", destination: "/tools/file-tools/file-splitter", permanent: true },
  { source: "/tools/file-metadata", destination: "/tools/file-tools/file-metadata", permanent: true },
  { source: "/tools/number-base-converter", destination: "/tools/math-tools/number-base-converter", permanent: true },
  { source: "/tools/percentage-calculator", destination: "/tools/math-tools/percentage-calculator", permanent: true },
  { source: "/tools/roman-numeral-converter", destination: "/tools/math-tools/roman-numeral-converter", permanent: true },
  { source: "/tools/fraction-calculator", destination: "/tools/math-tools/fraction-calculator", permanent: true },
  { source: "/tools/statistics-calculator", destination: "/tools/math-tools/statistics-calculator", permanent: true },
  { source: "/tools/scientific-calculator", destination: "/tools/math-tools/scientific-calculator", permanent: true },
  { source: "/tools/gif-maker", destination: "/tools/gif-tools/gif-maker", permanent: true },
  { source: "/tools/gif-compressor", destination: "/tools/gif-tools/gif-compressor", permanent: true },
  { source: "/tools/gif-to-mp4", destination: "/tools/gif-tools/gif-to-mp4", permanent: true },
  { source: "/tools/gif-to-png", destination: "/tools/image-tools/gif-to-png", permanent: true },
  { source: "/tools/gif-to-apng", destination: "/tools/gif-tools/gif-to-apng", permanent: true },
  { source: "/tools/apng-to-gif", destination: "/tools/gif-tools/apng-to-gif", permanent: true },
  { source: "/tools/mp4-to-gif", destination: "/tools/gif-tools/mp4-to-gif", permanent: true },
  { source: "/tools/mov-to-gif", destination: "/tools/gif-tools/mov-to-gif", permanent: true },
  { source: "/tools/avi-to-gif", destination: "/tools/gif-tools/avi-to-gif", permanent: true },
  { source: "/tools/webm-to-gif", destination: "/tools/gif-tools/webm-to-gif", permanent: true },
  { source: "/tools/background-remover", destination: "/tools/ai-tools/background-remover", permanent: true },
  { source: "/tools/grammar-fixer", destination: "/tools/ai-tools/grammar-fixer", permanent: true },
  { source: "/tools/ai-chatbot", destination: "/tools/ai-tools/ai-chatbot", permanent: true },
  { source: "/tools/ai-detector", destination: "/tools/ai-tools/ai-detector", permanent: true },
  { source: "/tools/ai-paraphraser", destination: "/tools/ai-tools/ai-paraphraser", permanent: true },
  { source: "/tools/ai-translator", destination: "/tools/ai-tools/ai-translator", permanent: true },
  { source: "/tools/ai-writer", destination: "/tools/ai-tools/ai-writer", permanent: true },
  { source: "/tools/audio-transcriber", destination: "/tools/ai-tools/audio-transcriber", permanent: true },
  { source: "/tools/data-extractor", destination: "/tools/ai-tools/data-extractor", permanent: true },
  { source: "/tools/email-generator", destination: "/tools/ai-tools/email-generator", permanent: true },
  { source: "/tools/image-captioner", destination: "/tools/ai-tools/image-captioner", permanent: true },
  { source: "/tools/qr-generator", destination: "/tools/qr-barcodes-tools/qr-generator", permanent: true },
  { source: "/tools/qr-scanner", destination: "/tools/qr-barcodes-tools/qr-scanner", permanent: true },
  { source: "/tools/barcode-generator", destination: "/tools/qr-barcodes-tools/barcode-generator", permanent: true },
  { source: "/tools/currency-converter", destination: "/tools/converter-tools/currency-converter", permanent: true },
  { source: "/tools/unit-converter", destination: "/tools/converter-tools/unit-converter", permanent: true },
  { source: "/tools/color-converter", destination: "/tools/converter-tools/color-converter", permanent: true },
  { source: "/tools/csv-to-excel", destination: "/tools/developer-tools/csv-to-excel", permanent: true },

  // --- /tools/media-tools/<slug> -> current category (media-tools was a real, live category before the split) ---
  { source: "/tools/media-tools/audio-booster", destination: "/tools/audio-tools/audio-booster", permanent: true },
  { source: "/tools/media-tools/audio-compressor", destination: "/tools/audio-tools/audio-compressor", permanent: true },
  { source: "/tools/media-tools/audio-converter", destination: "/tools/audio-tools/audio-converter", permanent: true },
  { source: "/tools/media-tools/audio-equalizer", destination: "/tools/audio-tools/audio-equalizer", permanent: true },
  { source: "/tools/media-tools/audio-merger", destination: "/tools/audio-tools/audio-merger", permanent: true },
  { source: "/tools/media-tools/audio-metadata", destination: "/tools/audio-tools/audio-metadata", permanent: true },
  { source: "/tools/media-tools/audio-splitter", destination: "/tools/audio-tools/audio-splitter", permanent: true },
  { source: "/tools/media-tools/audio-to-text", destination: "/tools/audio-tools/audio-to-text", permanent: true },
  { source: "/tools/media-tools/audio-trimmer", destination: "/tools/audio-tools/audio-trimmer", permanent: true },
  { source: "/tools/media-tools/audio-waveform", destination: "/tools/audio-tools/audio-waveform", permanent: true },
  { source: "/tools/media-tools/voice-recorder", destination: "/tools/audio-tools/voice-recorder", permanent: true },
  { source: "/tools/media-tools/gif-compressor", destination: "/tools/gif-tools/gif-compressor", permanent: true },
  { source: "/tools/media-tools/gif-maker", destination: "/tools/gif-tools/gif-maker", permanent: true },
  { source: "/tools/media-tools/media-player", destination: "/tools/video-tools/media-player", permanent: true },
  { source: "/tools/media-tools/screen-recorder", destination: "/tools/video-tools/screen-recorder", permanent: true },
  { source: "/tools/media-tools/subtitle-generator", destination: "/tools/video-tools/subtitle-generator", permanent: true },
  { source: "/tools/media-tools/video-compressor", destination: "/tools/video-tools/video-compressor", permanent: true },
  { source: "/tools/media-tools/video-converter", destination: "/tools/video-tools/video-converter", permanent: true },
  { source: "/tools/media-tools/video-filter", destination: "/tools/video-tools/video-filter", permanent: true },
  { source: "/tools/media-tools/video-merger", destination: "/tools/video-tools/video-merger", permanent: true },
  { source: "/tools/media-tools/video-metadata", destination: "/tools/video-tools/video-metadata", permanent: true },
  { source: "/tools/media-tools/video-resizer", destination: "/tools/video-tools/video-resizer", permanent: true },
  { source: "/tools/media-tools/video-rotator", destination: "/tools/video-tools/video-rotator", permanent: true },
  { source: "/tools/media-tools/video-screenshot", destination: "/tools/video-tools/video-screenshot", permanent: true },
  { source: "/tools/media-tools/video-to-audio", destination: "/tools/video-tools/video-to-audio", permanent: true },
  { source: "/tools/media-tools/video-to-gif", destination: "/tools/video-tools/video-to-gif", permanent: true },
  { source: "/tools/media-tools/video-trimmer", destination: "/tools/video-tools/video-trimmer", permanent: true },
  { source: "/tools/media-tools/video-watermark", destination: "/tools/video-tools/video-watermark", permanent: true },

  // --- one-off moves ---
  // media-tools had no single successor; video-tools got the majority of its
  // pages (15 of 28: every video tool plus media-player/screen-recorder/
  // subtitle-generator) and is the closer semantic match to "media" than the
  // narrower audio-tools or gif-tools splits.
  { source: "/tools/media-tools", destination: "/tools/video-tools", permanent: true },
  { source: "/login", destination: "/signin", permanent: true },
];
