// P33 (05/10): the OCR languages PDF OCR offers -- Tesseract codes (tessdata) and English names. Client-safe (no
// process.env, no server import): read by the page (app/lib/ocrLanguages.js adds the native names and the search), by
// /api/pdf-ocr (lib/pdfOcr.js refuses any other code) and by scripts/p33/ocr-languages.test.mjs, which checks that
// services/pdf-tools/Dockerfile installs one Debian model per code and that the service's /health lists them all.
const LANGUAGES = [
  { code: 'afr', label: "Afrikaans" },
  { code: 'sqi', label: "Albanian" },
  { code: 'amh', label: "Amharic" },
  { code: 'ara', label: "Arabic" },
  { code: 'asm', label: "Assamese" },
  { code: 'aze', label: "Azerbaijani" },
  { code: 'aze_cyrl', label: "Azerbaijani - Cyrillic" },
  { code: 'eus', label: "Basque" },
  { code: 'bel', label: "Belarusian" },
  { code: 'ben', label: "Bengali" },
  { code: 'bos', label: "Bosnian" },
  { code: 'bul', label: "Bulgarian" },
  { code: 'mya', label: "Burmese" },
  { code: 'cat', label: "Catalan; Valencian" },
  { code: 'ceb', label: "Cebuano" },
  { code: 'khm', label: "Central Khmer" },
  { code: 'chr', label: "Cherokee" },
  { code: 'chi_sim', label: "Chinese - Simplified" },
  { code: 'chi_tra', label: "Chinese - Traditional" },
  { code: 'hrv', label: "Croatian" },
  { code: 'ces', label: "Czech" },
  { code: 'dan', label: "Danish" },
  { code: 'nld', label: "Dutch; Flemish" },
  { code: 'dzo', label: "Dzongkha" },
  { code: 'eng', label: "English" },
  { code: 'enm', label: "English, Middle (1100-1500)" },
  { code: 'epo', label: "Esperanto" },
  { code: 'est', label: "Estonian" },
  { code: 'fin', label: "Finnish" },
  { code: 'fra', label: "French" },
  { code: 'frm', label: "French, Middle (ca. 1400-1600)" },
  { code: 'glg', label: "Galician" },
  { code: 'kat', label: "Georgian" },
  { code: 'kat_old', label: "Georgian - Old" },
  { code: 'deu', label: "German" },
  { code: 'frk', label: "German Fraktur" },
  { code: 'grc', label: "Greek, Ancient (-1453)" },
  { code: 'ell', label: "Greek, Modern (1453-)" },
  { code: 'guj', label: "Gujarati" },
  { code: 'hat', label: "Haitian; Haitian Creole" },
  { code: 'heb', label: "Hebrew" },
  { code: 'hin', label: "Hindi" },
  { code: 'hun', label: "Hungarian" },
  { code: 'isl', label: "Icelandic" },
  { code: 'ind', label: "Indonesian" },
  { code: 'iku', label: "Inuktitut" },
  { code: 'gle', label: "Irish" },
  { code: 'ita', label: "Italian" },
  { code: 'ita_old', label: "Italian - Old" },
  { code: 'jpn', label: "Japanese" },
  { code: 'jav', label: "Javanese" },
  { code: 'kan', label: "Kannada" },
  { code: 'kaz', label: "Kazakh" },
  { code: 'kir', label: "Kirghiz; Kyrgyz" },
  { code: 'kor', label: "Korean" },
  { code: 'kmr', label: "Kurdish (Kurmanji)" },
  { code: 'lao', label: "Lao" },
  { code: 'lat', label: "Latin" },
  { code: 'lav', label: "Latvian" },
  { code: 'lit', label: "Lithuanian" },
  { code: 'mkd', label: "Macedonian" },
  { code: 'msa', label: "Malay" },
  { code: 'mal', label: "Malayalam" },
  { code: 'mlt', label: "Maltese" },
  { code: 'mar', label: "Marathi" },
  { code: 'nep', label: "Nepali" },
  { code: 'nor', label: "Norwegian" },
  { code: 'ori', label: "Oriya" },
  { code: 'pan', label: "Panjabi; Punjabi" },
  { code: 'fas', label: "Persian" },
  { code: 'pol', label: "Polish" },
  { code: 'por', label: "Portuguese" },
  { code: 'pus', label: "Pushto; Pashto" },
  { code: 'ron', label: "Romanian; Moldavian; Moldovan" },
  { code: 'rus', label: "Russian" },
  { code: 'san', label: "Sanskrit" },
  { code: 'srp', label: "Serbian" },
  { code: 'srp_latn', label: "Serbian - Latin" },
  { code: 'sin', label: "Sinhala; Sinhalese" },
  { code: 'slk', label: "Slovak" },
  { code: 'slv', label: "Slovenian" },
  { code: 'spa', label: "Spanish; Castilian" },
  { code: 'spa_old', label: "Spanish; Castilian - Old" },
  { code: 'swa', label: "Swahili" },
  { code: 'swe', label: "Swedish" },
  { code: 'syr', label: "Syriac" },
  { code: 'fil', label: "Filipino (Tagalog)" },
  { code: 'tgk', label: "Tajik" },
  { code: 'tam', label: "Tamil" },
  { code: 'tel', label: "Telugu" },
  { code: 'tha', label: "Thai" },
  { code: 'bod', label: "Tibetan" },
  { code: 'tir', label: "Tigrinya" },
  { code: 'tur', label: "Turkish" },
  { code: 'uig', label: "Uighur; Uyghur" },
  { code: 'ukr', label: "Ukrainian" },
  { code: 'urd', label: "Urdu" },
  { code: 'uzb', label: "Uzbek" },
  { code: 'uzb_cyrl', label: "Uzbek - Cyrillic" },
  { code: 'vie', label: "Vietnamese" },
  { code: 'cym', label: "Welsh" },
  { code: 'yid', label: "Yiddish" },
];

const LANGUAGE_CODES = new Set(LANGUAGES.map((l) => l.code));

module.exports = { LANGUAGES, LANGUAGE_CODES };
