'use client';
import { useState } from 'react';
import SeoContent from '../../../components/SeoContent';
import { jsonToCode } from '../../../lib/jsonCodegen';
import { TextDownload } from '../../../components/FileDownload';
import { useToolError } from '../../../lib/useToolError';
import TextArea from '@/app/components/TextArea';
export default function JsonToGoPage() {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');
  const [error, setError] = useToolError('');
  const convert = async () => {
    try {
      setOutput(await jsonToCode(input, 'go'));
      setError('');
    } catch(e) { setOutput(''); setError('Invalid JSON: ' + e.message); }
  };
  return (
    <div className="min-h-screen bg-neutral-100 p-6">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold text-center mb-2">JSON to Go Struct</h1>
        <p className="text-neutral-500 text-center mb-8">Generate Go structs from JSON</p>
        <div className="bg-white border border-neutral-200 rounded-xl shadow-sm p-6 space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div><label className="block text-sm text-neutral-500 mb-1">JSON Input</label><TextArea className="w-full bg-neutral-50 border border-neutral-200 rounded-xl p-4 text-sm h-64 resize-none font-mono" placeholder='{"name":"John","age":30}' value={input} onChange={e => setInput(e.target.value)} /></div>
            <div><label className="block text-sm text-neutral-500 mb-1">Go Struct Output</label><TextArea aria-label="Go Struct Output" className="w-full bg-neutral-50 border border-neutral-200 rounded-xl p-4 text-sm h-64 resize-none font-mono" value={output} readOnly />
            <TextDownload text={output} name="model.go" /></div>
          </div>
          {error && <p className="text-red-400 text-center">{error}</p>}
          <div className="grid grid-cols-2 gap-3">
            <button onClick={convert} disabled={!input} className="bg-indigo-600 hover:bg-indigo-500 disabled:bg-neutral-200 disabled:text-gray-600 rounded-xl py-3 font-semibold transition text-white">Convert</button>
            <button onClick={() => navigator.clipboard.writeText(output)} disabled={!output} className="bg-green-600 hover:bg-green-500 disabled:bg-neutral-200 disabled:text-gray-600 rounded-xl py-3 font-semibold transition text-white">Copy</button>
          </div>
        </div>
      </div>
      <SeoContent
        title={"JSON to Go Struct"}
        description={"JSON to Go Struct turns a JSON sample into Go type declarations for encoding/json, generated by quicktype-core in your browser. Each nested object becomes its own named struct, field names follow Go style including initialisms (user_id becomes UserID), and every field keeps the original key in a json tag. Whole numbers are int64 and numbers written with a decimal point are float64. When you paste an array, a key that only some elements have becomes a pointer with omitempty. The output holds only the type definitions: no package line, no methods, no marshal helpers."}
        example={{
          caption: "One object with a nested address: the address gets its own struct.",
          inputLabel: "JSON Input",
          input: "{\"user_id\": 42, \"score\": 9.5, \"tags\": [\"go\", \"api\"], \"address\": {\"city\": \"Montreal\", \"zip\": \"H2X\"}}",
          outputLabel: "Go Struct Output",
          output: "type Root struct {\n\tUserID  int64    `json:\"user_id\"`\n\tScore   float64  `json:\"score\"`\n\tTags    []string `json:\"tags\"`\n\tAddress Address  `json:\"address\"`\n}\n\ntype Address struct {\n\tCity string `json:\"city\"`\n\tZip  string `json:\"zip\"`\n}",
        }}
        howToTitle={"How to convert JSON to a Go struct"}
        howTo={[
          "Paste the JSON, for example an API response, into \"JSON Input\".",
          "Click \"Convert\" to build the structs in \"Go Struct Output\".",
          "Add your own package line above the types, since the tool writes only the declarations.",
          "Click \"Copy\", or \"Download\" to get the file \"model.go\".",
        ]}
        specs={[
          { label: "Input", value: "JSON text; with an array, the fields of all elements are merged" },
          { label: "Output", value: "Go struct declarations with json tags, saved as model.go" },
          { label: "Number types", value: "int64 for whole numbers; float64 for numbers written with a point or an exponent, such as 10.0" },
          { label: "Optional keys", value: "Pointer type plus omitempty when a key is missing from some elements; pointer alone when it is null in some; interface{} when it is null in every sample" },
          { label: "Mixed types", value: "A key that holds a number in one element and text in another becomes a struct with Integer and String pointer fields; encoding/json cannot fill it without an UnmarshalJSON method you write" },
        ]}
        privacyTitle={"Where your JSON is processed"}
        privacy={"Struct generation runs in this browser tab. The quicktype engine is fetched once, on your first click, and your JSON stays on your computer. The page does send error reports: when a red error line appears, its wording, with quoted parts, long numbers and addresses stripped, goes to our error log along with the tool name and the name and version of your browser, and an unexpected failure of the page is reported the same way."}
        faqs={[
          { q: "Is a field a pointer when a key is sometimes missing or null?", a: "Yes. A key missing from at least one element becomes a pointer with omitempty, which leaves it out when encoding; a key that is null in one element becomes a plain pointer, without omitempty. If the key is always set in your real data, change *string to string by hand." },
          { q: "Which number types does it use?", a: "int64 for whole numbers and float64 for decimals. A value written as 10.0 counts as a decimal, so it becomes float64 and a later 10.5 still decodes. Switch to int or int32 yourself if your values are small." },
          { q: "How does it name fields from snake_case keys?", a: "It turns them into exported Go names and keeps the key in the tag: user_id becomes UserID, and its tag still says user_id, so encoding/json reads and writes the original key unchanged." },
          { q: "Can it generate a struct for a JSON array?", a: "Yes. A top-level array gives type Root []RootElement, and the fields of all elements are merged into RootElement, so one element without a key is enough to mark that key optional." },
        ]}
        tips={[
          "Paste two or three different items from an API list rather than one, so that keys that are sometimes absent become pointers.",
        ]}
      />
    </div>
  );
}